installation/build_install.md, output/README.md
I fixed some documentations.
* add new option and plugins.
* fix broken link.
* remove extra cell.
=> update some docs.

installation/unit_tests.md
I fixed unit_test.md to support new option format "FLB_TESTS".
=> unit_test: fix option name

development/library_api.md
I modified return values of library API.
They return a negative number like `open(2)`
=> development: modify return value of API

input/README.md
I fixed table of Input plugins.
The title of in_random was blanked.
=> input: add title of in_random to README.md of input

input/head.md
I added explanation of `add_path` which I committed https://github.com/fluent/fluent-bit/pull/140
=> in_head: add description about add_path

input/proc.md
I updated a documentation about in_proc.
* update sample output.
* add description about "fd" and "mem" options.
=> in_proc: add 'mem' and 'fd' options and update sample output

output/file.md
I added a description about file format which out_file supports.
See also
https://github.com/fluent/fluent-bit/pull/241
=> out_file: add description about file format

input/head.md
I added properties "lines" and "split_line" of in_head and its usecase.
These properties are added by https://github.com/fluent/fluent-bit/pull/295
=> in_head: add properties 'lines' and 'split_line'

parser/README.md
I added an explanation about `types` of parser plugin.
note : The feature is supported by https://github.com/fluent/fluent-bit/pull/310
=> parser: add explanation about 'types'

book.json
To fix version info.
<title> of official documentation indicates old version v0.11.
http://fluentbit.io/documentation/0.12
``` html
<head>
<title>Introduction · Fluent Bit v0.11 Documentation</title>
<meta charset="UTF-8">
```
=> book: update version

installation/build_install.md
In the build and install instructions, there is no longer the need to
create the "build" directory, since this is already included in the
fluent-bit source.
=> Remove instruction to create build directory

filter/kubernetes.md
A couple of Kubernetes filter config options didn't make it to the docs. The descriptions are mostly from the commit messages. Related to https://github.com/fluent/fluent-bit/issues/367.
=> Update kubernetes filter docs

output/http.md
This is doc for: https://github.com/fluent/fluent-bit/pull/475
=> Add docs for http output to send tag in header

output/splunk.md
Adds more information about the output format of the Splunk plugin and adds an example of using `Splunk_Send_Raw` to customize event metadata.
=> add details about splnuk output format

output/http.md
While reading the manual, I noticed several errors. This patch
contains a collection of fixes for it.
=> out_http: Fix typos and grammatical errors.

output/http.md
I think `-o stdout` is misplaced here, because running the current
version results in the following warning.
[ warn] [router] NO match for http.0 output instance
I confirmed in my console that removing `-o stdout` fixes the issue.
=> out_http: Fix the command-line configuration example

.gitignore, filter/kubernetes.md, input/tail.md
Document the filter_kubernetes fields:
- Merge_Log_Tream
- Kube_Meta_Preload_Cache_Dir
- Dummy_Meta
Document the input_tail fields:
- Tag
- Tag_Regex
=> Document missing Kubernetes fields (Tag, Tag_Regex, Meta, Trim)

output/forward.md
Recent Fluentd versions support SSL/TLS forward out of the box.
This patch adds a minimum example to enable the support.
This should close #52.
=> Explain how to encrypt connections using TLS (for fluentd v1.x)

output/bigquery.md
Documentation for the BigQuery output plugin added in https://github.com/fluent/fluent-bit/pull/925.
=> output: bigquery: document new Google Cloud BigQuery plugin

output/file.md
This PR add description of `plain` format for `file` output. It was added [here](https://github.com/fluent/fluent-bit/pull/694) but not described in documentation.
=> Add description of plain format to file output

parser/json.md
The example's time format didn't match the time format in the JSON
=> Fix documentation for json parser

installation/kubernetes.md
Point to https://docs.fluentbit.io with the correct version number.
=> Fix link URLs in kubernetes.md

output/kafka.md
Kafka pipelines into e.g. Druid prefer ISO8601 format over 'Double'
=> Add `Timestamp_Format` in Kafka output

output/http.md
This option was added to fluent-bit in PR https://github.com/fluent/fluent-bit/pull/1111.
Signed-off-by: James J. Goodhouse <j.goodhouse@gmail.com>
=> output_http: add _epoch_ option to json_date_format

output/http.md
This was added to the code in
(4ce354ec3)[https://github.com/fluent/fluent-bit/commit/4ce354ec3]
but does not seem to have been added to the docs.
=> [out_http] Add gelf format to docs

output/influxdb.md, output/kafka-rest-proxy.md, output/splunk.md
Noticed some TLS/SSL links in the output plugins were outdated or inconsistent.
=> Fix tls links

output/forward.md
Relates to fluent-bit PR fluent.fluent-bit#1321  : forward: implement 'require_ack_response'
Signed-off-by: Jukka Pihl <ext-jukka.pihl@elisa.fi>
=> out_forward: send_options and require_ack_response docs added.

output/elasticsearch.md
This adds a FAQ section to explain the recent backward-incompatible
changes added to the Index/Type feature.
Apparently this is being the source of confusion among Elasticsearch
users. So let's explain it clearly.
=> output: elasticsearch: add FAQ for errors occuring due to multiple types

input/winlog.md
A new input plugin for handling Windows Event Log is being submitted
as pull request #1378 on fluent/fluent-bit.
This adds documentation for it, with the full list of configurable
params and a couple of usage examples.
=> input: winlog: document the new Windows Event Log plugin

SUMMARY.md, parser/README.md, parser/logfmt.md, parser/ltsv.md
ltsv and logfmt parsers are already supported, but there are no document.
- Add new parser: ltsv https://github.com/fluent/fluent-bit/pull/646
- Add new parser: logfmt https://github.com/fluent/fluent-bit/pull/871
I added the document about them.
=> add description about ltsv and logfmt parsers

filter/parser.md
As noted by #151, the documentation is incorrect.
Reserved_Data and Preserved_Key should be activated in the [FILTER] block instead of the [PARSER] block.
Also, Preserved_Key only works when Reserved_Data is On.
This is why I've swap the block in the documentation.
Relevant part in the code: https://github.com/fluent/fluent-bit/blob/master/plugins/filter_parser/filter_parser.c
```
if (ctx->reserve_data) {
if (!ctx->preserve_key) {
append_arr_i--;
append_arr_len--;
append_arr[append_arr_i] = NULL;
}
}
else {
continue_parsing = FLB_FALSE;
break;
}
```
I don't actually know what the code do, but I couldn't get the documentation's example working and preserve_key seems to be only invoked here.
=> filter: parser: Reserve_Data should be activated in FILTER

service/README.md
We can set `error/warning/info/debug/trace` as `Log_Level`.
=> service: modify 'Log_Level' data type

parser/regular_expression.md
This is a limitation of Onigumo, who throws an initialization error
if a group name contains characters other than alphanumeric.
Let's document the limitation in the manual page clearly so that
users do not get confused about it.
=> parser: regular_expression: Add warning about special characters

configuration/file.md
libco assumes that Coro_Stack_Size is large enough to hold the coroutine
thread's call stack.
Setting too small value to this configuration item can break the implicit
assumption, and can lead to obnoxious errors due to memory corruptions.
Let's document this issue clearly.
=> configuration: file: Document the risk of too small Coro_Stack_Size

filter/lua.md
From looking at the source code, up to 16 keys can be used. Updated to reflect this.
=> Document Type_int_key for multiple keys

SUMMARY.md, output/README.md, output/datadog.md
This is a new page in the output section to support the upcoming release of the Datadog integration.
=> Adding a documentation page for Datadog

installation/windows.md
* This adds a list of available installers to the documentation.
* Checksums are meant for users who want to check the integrity of
downloaded packages.
=> installation: add the list of Windows installers (and their checksums)

input/disk.md, input/netif.md
(Arguably) Disk usage is usually referring to utilisation of available space (is my disk nearly full), rather than read and write throughput.
=> input: clarify that both disk and netif are throughput oriented

output/file.md
This explains how to use the newly-added "Template" formatter
and also adds some basic configuration example.
https://github.com/fluent/fluent-bit/pull/1480
=> out_file: add documentation for template format

input/syslog.md
This is meant to be a suppliment to the main patch currently
submitteed at fluent/fluent-bit/issues/1554
I added the description for the option to the parameter list and
updated the configuration example.
=> input: syslog: docment 'Unix_Perm' option

output/forward.md
This documents the upcoming "Username" and "Password" parameters,
which enables Fluent Bit to connect to a Fluentd server that forces
password authentication.
NOTE the main patch is being submitted at https://github.com/fluent/fluent-bit/pull/1574.
=> output: forward: Add Username and Password options

parser/README.md
To make clear which parser supports `Types` option.
https://github.com/fluent/fluent-bit/issues/1563
> Clearly states in the documentation that this is working as intended and it can be used only with the other parser (like the Decode_Fieldkey that on the contrary work only on json parsers).
=> parser: specify parsers which support Types option

configuration/tls_ssl.md
Also adds a configuration example to illustrate what is the good
of `tls.vhost` option and how to use it.
This is a supplemental material of fluent/fluent-bit/pull/1313.
=> configuration: tls: document tls.vhost option

output/azure.md
I've updated the Azure docs a bit. I think it's more accurate if the desired Azure service is explicitly referenced instead of just referring to it as *Azure*
=> fix(typos): Make instructions for Azure LogInsights a bit more clear

input/syslog.md
```
Chunk_Size  -> Buffer_Chunk_Size
Buffer_Size -> Buffer_Max_Size
```
=> in_syslog: fix parameter names to match names in examples

configuration/file.md
kaizen1 pointed out that the explanation about `Match` is unclear
about what it is supposed to match *against*. This seems to be
somewhat confusing to new users.
This sorts out the description, and clarify the usage of `Match`
and its family options.
The original issue is fluent/fluent-bit/issues/1792
=> configuration: file: Add better explanation for `Match` option

output/forward.md
This option is a special configuration to connect to Fluentd nodes
that use zero-length strings (a.k.a. "") as shared secrets. Let's
document it.
=> output: forward: Document 'Empty_Shared_Key'

installation/build_install.md
In response to https://github.com/fluent/fluent-bit/pull/1198
Make the development options a bit more discoverable in the documentation.
Signed-off-by: Nigel Stewart <nigels@nigels.com>
=> build_install: Development-oriented cmake options

output/http.md
I did some integration of fluent-bit into a [Sumo Logic](https://www.sumologic.com) dashboard for a Raspberry Pi version 1.
Aligning the `http` output for Sumo Logic is a little bit non-obvious, so I documented some settings that seem to work well for me.  Specifically the `timestamp` and `json_lines` format.
=> output: http: Sample config and query for Sumo Logic usage

input/collectd.md
The parameter name for the address to listen on is "Listen", not "Address": https://github.com/fluent/fluent-bit/blob/master/plugins/in_collectd/in_collectd.c#L93
Signed-off-by: Marc Richards <talawahtech@users.noreply.github.com>
=> input: collectd: Fix parameter name and typo

installation/td-agent-bit.md
ref: https://docs.fluentbit.io/manual/installation/raspberry_pi
Signed-off-by: Kentaro Hayashi <hayashi@clear-code.com>
=> installation: td-agent-bit: add missing Raspbian stretch support

SUMMARY.md, input/README.md, input/docker.md
We added a new input plugin to collect metrics from running Docker
containers (see d19be0d765 in fluent/fluent-bit).
This adds the documentation for the new plugin, explaining the list
of available parameters and its basic usage.
Fixes #222 
=> Document in_docker plugin

input/exec.md
This was added in this PR: fluent/fluent-bit#1116
=> Update exec documentation to include `buf_size`

SUMMARY.md, input/README.md, input/statsd.md
We have recently implemented a new plugin to receive metrics via
StatsD protocol (will be included in Fluent Bit v1.4.0).
This documents the configuration parameters of the new plugin and
its basic usage.
=> input: statsd: add documentation for the new "in_statsd" plugin

configuration/variables.md
This commit fixes to minor spelling mistakes and applies markdown code formatting instead of a mix of escapes and italics.
=> Minor spelling and markdown code formatting

output/elasticsearch.md
Document Trace_Error which outputs to console elasticsearch API calls when there is an error
=> output: Add an undocumented parameter for Elasticsearch

installation/sources/build-and-install.md
The default version of CMake on CentOS 7 is 2.x. For this reason,
we keep hearing complaints that cmake fails to set up the build
directory.
Fix that by documenting the version requirement clearly.
=> installation: sources: build-and-install: Document CMake 3.x

administration/configuring-fluent-bit/configuration-file.md
I spent a while trying to figure out why config like this wasn't working:
`config-main.conf`:
```
[SERVICE]
Daemon Off
$INCLUDE config-extra.conf
```
`config-extra.conf`:
```
[SERVICE]
Parser_File parsers_extra.conf
```
Hopefully this docs addition will save others 🙏
=> Clarify @INCLUDE limitations

SUMMARY.md, local-testing/logging-pipeline.md
It is not uncommon to want to see how a logging pipeline works locally, this can be achieved with docker.
This is, imho, the easiest way for operators to validate logging pipelines locally as to troubleshoot and catch bugs as done in https://github.com/fluent/fluent-bit/issues/2093
=> Add instructions to run a logging pipeline locally with docker.

pipeline/filters/lua.md
filter_lua supports protected mode. https://github.com/fluent/fluent-bit/pull/2154
This is a patch for it.
=> pipeline: filter: lua: add description about protected_mode

pipeline/filters/parser.md
Copied from
https://fluentbit.io/documentation/0.13/parser/#time-resolution-and-fractional-seconds
=> Re-add "Time Resolution and Fractional Seconds"

pipeline/parsers/regular-expression.md
Fluent Bit uses Onigmo as the regex backend. It is known that Onigmo
is vulnerable to ReDoS i.e. it uses exponential computation time on
a certain type of expressions.
Add a clear warning about it, so that our users can exercise caution
when writing their configurations.
=> pipeline: parser: Add a warning on ReDoS

pipeline/outputs/stackdriver.md, pipeline/outputs/stackdriver_special_fields.md
Update the doc of Stackdriver - Support special field `operation`.
Signed-off-by: scgao <scgao@google.com>
=> output:stackdriver: Support special fields - operation

pipeline/inputs/tail.md
The example for `Exclude_Path` for the `tail` input uses an incorrect syntax.
=> pipeline: input: tail: fix Exclude_Path example typo

concepts/buffering.md, concepts/data-pipeline/buffer.md, concepts/key-concepts.md, installation/upgrade-notes.md, pipeline/outputs/elasticsearch.md
- in v1.5, the default `type` was changed, which can cause problems. Highlighted this in the upgrade notes and added a 'FAQ' to the `out_es` page.
- since v1.5 introduces aws auth support, added more text to highlight that `AWS\_Region` is required. If not, it dies at runtime. Seems like it could be inferred, but at least the docs reflect it a little better.
- minor copyedits throughout.
cc @edsiper because it builds on the commit you just made about ES types, @PettitWesley for general AWS knowledge.
=> outputs: add docs around v1.5 out_es change to ES type; copyedits

installation/windows.md
This adds a basic explanation on how to register & manipulate
Fluent Bit as Windows Service.
This should be useful for users who want to install Fluent Bit to
their Windows servers.
=> installation: windows: Document "Windows Service"

pipeline/outputs/cloudwatch.md
Updates the `out_cloudwatch_logs`  documentation config section to add `cw-emf` metrics namespace and dimension support.
Signed-off-by: Rayhan Hossain <hossain.rayhan@outlook.com>
=> out_cloudwatch_logs: update config section documentation for CW EMF support

administration/configuring-fluent-bit/configuration-file.md
https://docs.fluentbit.io/ seems missing grace key in Service section once existed in the document for ver1.3.
* v1.4/1.5: https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/configuration-file
* v1.3: https://docs.fluentbit.io/manual/v/1.3/service
It seems the code still has the grace key 
https://github.com/fluent/fluent-bit/blob/master/include/fluent-bit/flb_config.h#L50
This pr is to re-add the grace key once existed in the previous minor version.
reference: https://github.com/fluent/fluent-bit/issues/2563
Signed-off-by: Kengo Suzuki <kengoscal@gmail.com>
=> add Grace key in service

pipeline/outputs/tcp-and-tls.md
Current result with `nc -l 6666` I get `[error] [io] connection #19 failed to: 127.0.0.1:6666`:
```machine@buster:~/fluent-bit/build$ bin/fluent-bit -i cpu -o tcp://127.0.0.1:6666 -p format=json_lines -v
Fluent Bit v1.6.0
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io
[2020/09/18 20:40:45] [ info] Configuration:
[2020/09/18 20:40:45] [ info]  flush time     | 5.000000 seconds
[2020/09/18 20:40:45] [ info]  grace          | 5 seconds
[2020/09/18 20:40:45] [ info]  daemon         | 0
[2020/09/18 20:40:45] [ info] ___________
[2020/09/18 20:40:45] [ info]  inputs:
[2020/09/18 20:40:45] [ info]      cpu
[2020/09/18 20:40:45] [ info] ___________
[2020/09/18 …
```
=> tcp-and-tls: fix netcat missing '-p' port keyword

pipeline/inputs/tail.md
Clarify that the path pattern cannot match the rotated files; otherwise,
the rotated files would get read again and lead to duplicate records.
While there, fix some minor grammar and formatting issues.
Signed-off-by: Aaron LI <aly@aaronly.me>
=> inputs/tail: Clarify path pattern and file rotation

installation/kubernetes.md
This explains the basic concept of Kubernetes deployment (e.g. which
file contain what), and shows how to set up Fluent Bit for Windows
logging.
It will be useful for Windows users to get started, and should resolve
the issue fluent-bit#2087.
=> installation: kubernetes: Document Windows deployment

administration/http-proxy.md, pipeline/outputs/http.md
This is for documenting the `HTTP_PROXY` support implemented in https://github.com/fluent/fluent-bit/pull/2694
Signed-off-by: Yu Yi <yiyu@google.com>
=> Doc for setting up http proxy via `HTTP_PROXY`

administration/monitoring.md
Pierre-Olivier Latour submitted an issue that asked if Windows builds
support HTTP monitoring. Evidently this seems to be a rather common
question among Windows users.
https://github.com/fluent/fluent-bit/issues/2696
Let's document the support state clearly in the documentation.
=> administration: monitoring: add note on Windows support

pipeline/inputs/tail.md
The last matched group in the regex defined by `Parser_Firstline` must be a string,
otherwise the contents of the multiline capture cannot be appended.
=> input: tail: clarify multiline parser requirement

pipeline/outputs/datadog.md
This documents the `Proxy` option added by fluent/fluent-bit#1844.
Signed-off-by: Lénaïc Huard <lenaic.huard@datadoghq.com>
=> output: datadog: Add new `Proxy` option

installation/windows.md
barney-s asked about how to compile Fluent Bit on Windows
(fluent/fluent-bit/issues/2390). Evidently, there is a certain interest among
corporate users to build Fluent Bit from scratch.
This adds the minimum procedure to accomplish that. I confirmed
this procedure works on Windows Server 2019 (but it should works
fine as well on older versions of Windows Server).
=> installation: windows: Document how to compile from source code

administration/configuring-fluent-bit/configuration-file.md
=> Logs by default seem to go to standard error

installation/kubernetes.md
If a CRI runtime, such as container or CRIO, is utilized, the user should update
the INPUT's parser from docker to cri.
Equivalent PR for kubernetes docs: https://github.com/fluent/fluent-bit-kubernetes-logging/pull/76
Ideally this PR will reference the configmap, rather than the sample flluent-bit repository's parsers.conf
Signed-off-by: Eric Ernst <eric@amperecomputing.com>
=> Add note on CRI for kubernetes configmap

pipeline/outputs/elasticsearch.md
This must have been removed in the docs transition because it's visible on the website [for the 1.3 docs](https://docs.fluentbit.io/manual/v/1.3/output/elasticsearch).
=> output: es: Add Trace_Error

installation/sources/build-and-install.md
FLB_TLS is set to "on" [if FLB_OUT_TD is on](https://github.com/fluent/fluent-bit/blob/1b262cebff01a2d54c7dab8ff5d3d8e340faed30/CMakeLists.txt#L247-L249). FLB_OUT_TD is on by default, so FLB_TLS is on by default.
=> Document FLB_TLS as on by default.

SUMMARY.md, pipeline/filters/geoip2.md
Commit 3785f8a added a new filter plugin `filter_geoip2`.
https://github.com/fluent/fluent-bit/commit/3785f8a5a50b9ededaaf732c06285e9dc88f551e
This adds the basic documentation for the new plugin.
=> filter: geoip2: Document GeoIP2 filter plugin

pipeline/inputs/tail.md
faced the issue which could be avoided if I saw this warning.
=> [INPUT] [Tail] Update the warning for DB parameter

pipeline/inputs/forward.md
`Unit Size` link is wrong in forward page.
https://docs.fluentbit.io/manual/pipeline/inputs/forward
=> Fix the link to the Unit Sizes

administration/configuring-fluent-bit/configuration-file.md
=> Fix Service config table to be an actual table

pipeline/outputs/elasticsearch.md
This PR adds documentation about Elastic cloud settings so as to connect Fluentbit to Elasticsearch running on Elastic Cloud.
Implementation PR: https://github.com/fluent/fluent-bit/pull/2834
=> Add es cloud section

pipeline/outputs/loki.md
Loki output plugin use default label `job=fluent-bit`
https://github.com/fluent/fluent-bit/blob/26426262ebdf606139af4a241e25ece3afe5451a/plugins/out_loki/loki.c#L373-L381
=> out_loki: fix loki output plugin default label

pipeline/filters/rewrite-tag.md
It is easily missed that the record under the new tag is re-emitted from the beginning of the pipeline. Also I aligned the usage of upper case for the keyword "Rule" to not be easily confused with the "Match rule".
=> improve wording of rewrite_tag recrod re-emitting

pipeline/outputs/stackdriver.md
Added keys for generic_node and generic_task.
- location
- namespace
- node_id
- job
- task_id
Signed-off-by: Joey DeStefanis <jdestefanis@google.com>
=> [out_stackdriver]: Add generic resource keys.

pipeline/outputs/forward.md
Currently, the doc says:
```
If the TAG parameter is not set, the plugin will set the tag as fluent_bit.
```
which is wrong.
=> Fix misleading TAG comment in output forward

pipeline/filters/kubernetes.md
This is for the documentation of [issue: 3025](https://github.com/fluent/fluent-bit/pull/3025)
Signed-off-by: Drew Zhang <zhayuzhu@amazon.com>
=> filter: kubernetes: add documentation for use_kubelet(#1948)

administration/monitoring.md
Fixing broken link.
```
The following example set an alias to the INPUT section which is using the CPU input plugin:
```
=> monitoring: fix broken link

pipeline/inputs/dummy.md
I added a description about `Samples` option of `in_dummy`.
It has not been documented  yet.
=> in_dummy: add description about Samples property

administration/configuring-fluent-bit/upstream-servers.md
Fix broken links.
https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/upstream-servers
```
this is the case of HTTP, Elasticsearch and Forward within others.
```
```
The following plugin(s) have Upstream support:
Forward
```
```
The TLS options available are described in the TLS/SSL section and can be added to the any Node section.
```
=> upstream-servers: fix broken links

pipeline/filters/lua.md
I fixed broken link.
https://docs.fluentbit.io/manual/pipeline/filters/lua
```
The following examples uses the dummy input plugin for data ingestion,
```
=> filter: lua: fix broken link

pipeline/outputs/gelf.md
fix broken links.
https://docs.fluentbit.io/manual/pipeline/outputs/gelf
`please refer to the TLS/SSL section.`
`If you're using Docker JSON parser, this parser can parse time`
`If you're using Fluent Bit in Kubernetes and you're using Kubernetes Filter Plugin,`
`If you use Tail Input and use a Parser like the docker parser shown above, it decodes your message and extracts data (and any other present) field. This is how this log in stdout looks like after decoding:`
`The Nest Filter, unnests fields inside log key`
`Kubernetes Filter adds host name.`
=> pipeline: outputs: gelf: fix broken link

pipeline/filters/rewrite-tag.md
Fix broken link.
https://docs.fluentbit.io/manual/pipeline/filters/rewrite-tag#monitoring
```
As described in the Monitoring section, every component of the pipeline of Fluent Bit exposes metrics.
```
=> pipeline: filters: rewrite-tag: fix broken link

pipeline/outputs/s3.md
- Match `stdout` doc wording
Based on this https://github.com/fluent/fluent-bit/issues/2700#issuecomment-882212296 by @PettitWesley and confirmed by testing, `json_date_key` is already supported by the S3 output processor but not included in the docs which confused me.
Wording updated to match [stdout](https://github.com/fluent/fluent-bit-docs/blob/master/pipeline/outputs/standard-output.md)
=> Include json_date_key in s3 output docs

administration/aws-credentials.md, pipeline/outputs/cloudwatch.md, pipeline/outputs/elasticsearch.md, pipeline/outputs/firehose.md, pipeline/outputs/kinesis.md, pipeline/outputs/s3.md
Added documentation for the AWS credential chain precedence hierarchy, including the recently added support for `credential_process`.
cc @PettitWesley
=> aws: add documentation for credentials chain

pipeline/outputs/splunk.md
Fix broken link.
https://docs.fluentbit.io/manual/pipeline/outputs/splunk#tls-ssl
```
Splunk output plugin supports TTL/SSL, for more details about the properties available and general configuration, please refer to the TLS/SSL section.
```
=> pipeline: outputs: splunk: fix broken link

pipeline/outputs/datadog.md
I added missing properties of out_datadog plugin.
- `proxy`
- #249 
-  `provider`
-  https://github.com/fluent/fluent-bit/pull/1579
- `json_date_key`
- https://github.com/fluent/fluent-bit/blob/v1.8.4/plugins/out_datadog/datadog.c#L188
- https://github.com/fluent/fluent-bit/blob/v1.8.4/plugins/out_datadog/datadog_conf.c#L170
- `include_tag_key`
- https://github.com/fluent/fluent-bit/blob/v1.8.4/plugins/out_datadog/datadog.c#L194
- https://github.com/fluent/fluent-bit/blob/v1.8.4/plugins/out_datadog/datadog_conf.c#L92
- `tag_key`
- https://github.com/fluent/fluent-bit/blob/v1.8.4/plugins/out_datadog/datadog.c#L197
- https://github.com/fluent/fluent-bit/blob/v1.8.4/plugins/out_datadog/datadog_conf.c#L103
- `dd_message_key`
- https://github.com/fluent/fluent-bit/blob/v1.8.4/plugins/out_datado …
=> out_datadog: add missing properties.

pipeline/filters/standard-output.md
Fix a error as mentioned in #358, **Standard Output** is already in Outputs chapter, so it needs to be deleted.
=> filter: rewrite the stdout plugin page

installation/aws-container.md
Added `kinesis_firehose` and `cloudwatch_logs` plugins into Core Fluent Bit Plugin.
* https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit#new-higher-performance-core-fluent-bit-plugin
* https://github.com/aws/amazon-kinesis-firehose-for-fluent-bit#new-higher-performance-core-fluent-bit-plugin
So, add descriptions about them.
=> Add explanations of kinesis_firehose and cloudwatch_logs

pipeline/outputs/prometheus-exporter.md
The patch https://github.com/fluent/fluent-bit/pull/4081 causes broken change.
User should use `host` to set hostname/IP address.
=> out_prometheus_exporter: replace listen -> host

pipeline/outputs/file.md
Fixes #534 
- `Path` should support absolute and relative path
- `Path` should be a directory path
=> out_file: fix 'path' description(#534)

administration/configuring-fluent-bit/configuration-file.md
This patch is to add description about https://github.com/fluent/fluent-bit/pull/4099
The feature is supported from v1.8.7.
https://github.com/fluent/fluent-bit/commits/v1.8.7
=> configuration-file: add 'scheduler.cap' and 'scheduler.base'

pipeline/filters/kubernetes.md
the _italic_ was \_breaking due to escape char \
Signed-off-by: pr0PM <pr0PM@pm.me>
=> Fix for tiny typo

pipeline/outputs/prometheus-remote-write.md
The example for sending prometheus metrics to New Relic sets the header "bearer_token" when it should be setting the header "Authorization". The former doesn't work, and results in a 400 response. The Logz.io and Coralogix examples already used the correct form, this just brings the main example into line.
=> Fix Authorization header in remote-write example

pipeline/inputs/fluentbit-metrics.md
Hi, I wanted to export fluentbit's own metrics via Prometheus remote-write. I spent quite a while looking at the [Fluent Bit monitoring docs][1] and scratching my head until a colleague pointed out that the `fluentbit_metrics` input plugin provides these metrics.
The `fluentbit_metrics` input plugin was undocumented. It's valuable for emitting these metrics via remote-write. This PR adds documentation similar to the documentation on the `node_exporter` input plugin.
I've manually tested the configuration in the example. I note that the node_exporter plugin [example][2] which I based it on fails due to having "listen" instead of "host" as a configuration key name.
Is this plugin considered public, are these docs useful? They would have helped me.
Are they okay as they are? I worry the …
=> Add documentation for fluentbit_metrics plugin

installation/sources/build-and-install.md
Build flag `FLB_OUT_NATS` seems to be enabled by default, according to the current CMakeLists.txt:
https://github.com/fluent/fluent-bit/blob/8c491202d62d996b7412726bb2c13f0761b887f6/CMakeLists.txt#L159
=> Build flag `FLB_OUT_NATS` is default to On

pipeline/outputs/syslog.md
Update the Syslog output doc:
- Add example of how to configure the structured data key.
- Update description.
- Update configuration parameters list to maintain consistency across all config options.
=> pipeline: outputs: syslog: add structured data example

pipeline/inputs/docker-events.md
This is a documentation of https://github.com/fluent/fluent-bit/pull/3440
=> in_docker_events: add parameters to reconnect with docker socket

pipeline/outputs/loki.md
This is a documentation about https://github.com/fluent/fluent-bit/pull/3260
=> out_loki: add description about 'tenant_id_key'

installation/sources/build-and-install.md
The link to the forward plugin in the build and install page is incorrect. Added the correct link.
=> Fixed wrong href

pipeline/filters/modify.md
Update filter_modify documentation.
- Fix wrong parameter for `Key_does_not_exist`
-  Same as `Key_exists`
- Support record accessor for Condition
- https://github.com/fluent/fluent-bit/pull/3695
=> Filter modify ra condition

pipeline/outputs/loki.md
Fix broken link.
https://docs.fluentbit.io/manual/pipeline/outputs/loki
```
that means that's a Record Accessor pattern so it provide you the ability to retrieve values from nested maps by using the key names.
```
=> pipeline: outputs: loki: fix broken link

installation/windows.md
There are some user reports regarding how to use Fluent Bit as
a Windows Service (e.g. fluent/fluent-bit/issues/3569).
Document common pitfalls and some other useful tips about Windows
Service management.
=> installation: windows: explain common pitfalls of Windows service

installation/windows.md
Executing `setx /m path` is dangerous. I've had various team members ruin their shell environment because it erased their Path env var. See e.g. https://stackoverflow.com/a/28778358/938297
This PR changes `setx /m path` to a description to add a directory to the environment variable Path in a non-destructive way.
=> windows: remove setx statement

administration/http-proxy.md
Signed-off-by: Yu Yi <yiyu@google.com>
=> Add documentation for `NO_PROXY` environment variable.

pipeline/parsers/configuring-parser.md
Fixes #514 
I added configuring-parser.md.
It is based on https://docs.fluentbit.io/manual/v/1.3/parser.
It is missing parser configuration documentation.
=> pipeline: parser: add configuring-parser.md (#514)

pipeline/inputs/forward.md
I updated the description to respect current implementation.
- fix default size of `buffer_chunk_size` and `buffer_max_size`
- https://github.com/fluent/fluent-bit/blob/548ff0169efbab81d282fb0e24e4bca1bf8073a5/plugins/in_forward/fw_conn.h#L24  
- add unix_path option
- https://github.com/fluent/fluent-bit/blob/548ff0169efbab81d282fb0e24e4bca1bf8073a5/plugins/in_forward/fw_config.c#L42
- remove forward://ip:port style
- Currently, `forward://127.0.0.1:12345` style will be `Invalid input type` error.
=> inputs: forward: update options

pipeline/filters/modify.md
I fixed broken link of filter_modify.
https://docs.fluentbit.io/manual/pipeline/filters/modify#example-1-add-and-rename
```
The following invokes the Memory Usage Input Plugin, which outputs the following (example),
```
=> filter: modify: fix broken link

pipeline/inputs/http.md
The property `type` was referenced instead of `name`, which made the example configuration invalid.
=> Fixed false property in example config for http input docs

pipeline/filters/nest.md
I fixed broken link.
https://docs.fluentbit.io/manual/pipeline/filters/nest
```
In order to start filtering records, you can run the filter from the command line or through the configuration file. The following invokes the Memory Usage Input Plugin, which outputs the following (example),
```
=> filters: nest: fix broken link

administration/security.md
Example working configuration
```
[OUTPUT]
Name loki
Match *
tls on
Host loki.example.com
Port 443
http_user loki
http_passwd 12345
```
=> Loki can also utilize TLS

pipeline/outputs/firehose.md
Remove "auto_create_group" option as it's not a valid option for firehose output plugin.
=> Remove "auto_create_group" option of Firehose output plugin.

pipeline/inputs/health.md
Currently, `health://127.0.0.1:80` style is not supported.
This patch is 
* To use `-p host=127.0.0.1 -p port=80` style.
* Update example log
=> pipeline: inputs: health: fix command line style

pipeline/filters/kubernetes.md
Adding some details on potentially azure-specific rolebinding issues where Azure doesn't permit kubernetes filter to retrieve data due to not being a member of `system:serviceaccounts`.
Regardless, also adding a quick way to check if the permissions are correctly set with the `can-i` command :)
=> Adds troubleshooting for Roles for AKS clusters

pipeline/outputs/splunk.md
I added new property `channel` to out_splunk.
This is a documentation for it.
https://github.com/fluent/fluent-bit/pull/3318
=> pipeline: outputs: splunk: add option 'channel'

pipeline/filters/lua.md
Add description about that the Lua callback can return an array of
records, i.e., the third return value of the callback function can be an
array of tables.  This feature enables this Lua filter to split an input
record into multiple records.  Document the record split feature as a
new subsection and add an example about it.
See also https://github.com/fluent/fluent-bit/pull/811 .
While there, variosu minor grammar and format fixes.
Signed-off-by: Weitian LI <liweitianux@live.com>
=> filter/lua: Document record split and many minor improvements

pipeline/filters/type-converter.md
Fixes #646 
I added a document for filter_type_converter plugin.
The plugin is already merged for v1.9.
https://github.com/fluent/fluent-bit/pull/4025
=> filter_type_converter: add documentation

administration/networking.md
remove documentation for parameters tcp_keepalive* that are not supported.
closes https://github.com/fluent/fluent-bit/issues/4415
=> administration: networking: remove tcp_keepalive* documentation

pipeline/outputs/elasticsearch.md
taken from https://github.com/uken/fluent-plugin-elasticsearch/blob/master/README.md#write_operation
=> feat: write_operation docs

pipeline/outputs/s3.md
This is a new feature of upcoming Fluent Bit v1.8 release.
* The Amazon S3 plugin now can store incoming data in Apache
Arrow format.
* This support is very convenient for data analysis and manipulation.
e.g. Use Fluent Bit to send real-time system statistics to S3
and do time-series analysis using pandas.
* For now, it needs a feature flag being turned on at compile time.
Not enabled on a default build.
Add documentation about the support, and explain how to make use
of the feature.
=> out_s3: add documentation for Apache Arrow support

installation/windows.md
Taken from: https://github.com/fluent/fluent-bit/pull/4647
This adds a default configuration file for Windows, in order
to provide a minimum set of configuration that can be used
as a starting point.
This should fix the bug report "Default config file doesn't work on
Windows" reported:
https://github.com/fluent/fluent-bit/issues/4635
https://github.com/fluent/fluent-bit/issues/4631
=> windows: provide sample config

pipeline/outputs/splunk.md
=> out_splunk: remove unsupported Message_Key from sample configuration

installation/linux/debian.md, installation/linux/raspbian-raspberry-pi.md, installation/linux/ubuntu.md
=> install: linux: add system upgrade recommendation

installation/sources/download-source-code.md
After discussion with Jorge decided to switch over to single source of truth being Github.
Not directly related to https://github.com/fluent/fluent-bit/issues/4709 but intended to help.
=> source: add Github links

installation/sources/download-source-code.md
* source: add Github links
* source: switch to Github
=> source: add Github links (#691)

pipeline/inputs/exec.md
Indicate that the `exec` plugin is non-functional in the production images: https://github.com/fluent/fluent-bit/issues/1758
=> exec: container support info

installation/docker.md
Addresses https://github.com/fluent/fluent-bit/issues/4645#issuecomment-1025464523 by ensuring we have the Debian 11 update in there.
=> docker: update 1.8.12 base image details

installation/linux/README.md, installation/linux/amazon-linux.md, installation/linux/debian.md, installation/linux/raspbian-raspberry-pi.md, installation/linux/redhat-centos.md, installation/linux/snap.md, installation/linux/ubuntu.md
Related to https://github.com/fluent/fluent-bit/pull/4740
=> installation: update to use new one line install and other fixes

installation/linux/README.md
=> install: fix script used

concepts/key-concepts.md, development/msgpack-format.md, pipeline/outputs/tcp-and-tls.md
Adds message pack format information to address https://github.com/fluent/fluent-bit/issues/4750.
Also updates the TCP examples for both JSON and MessagePack to correctly show output.
=> msgpack: examples for TCP and other info

administration/configuring-fluent-bit/configuration-file.md
In the recent documentation, the link to the config virtualization tool cannot open, due to the CORS policy from https://cloud-api.calyptia.com/
After digging, I think the link should be change to https://cloud.calyptia.com
=> change stale link due to CORS

SUMMARY.md, pipeline/inputs/fluentbit-metrics.md, pipeline/outputs/opentelemetry.md
Signed-off-by: Leonardo Alminana <leonardo@calyptia.com>
=> out_opentelemetry: initial commit

installation/sources/download-source-code.md
=> source: fix chevron parsing

pipeline/filters/parser.md
The property "unescape_key" is already removed and not supported.
https://github.com/fluent/fluent-bit/issues/453
=> filter_parser: remove 'unescape_key'

pipeline/outputs/bigquery.md
Added the new configuration parameters used for GCP workload identity federation. Updated these docs in sync with the changes in the main Fluent Bit repo.
Signed-off-by: zhenyami <zhenyamzk+GitHub@gmail.com>
=> out_bigquery: support AWS auth via GCP Workload Identity Federation

pipeline/outputs/stackdriver.md
Docs change for https://github.com/fluent/fluent-bit/pull/4753
Signed-off-by: Ridwan Sharif <ridwanmsharif@google.com>
=> out_stackdriver: Update docs to correct env var

pipeline/inputs/tail.md
=> input: tail: remove monitoring section

README.md
https://docs.fluentbit.io/manual/
```
Stream Processing: Perform data selection and transformation using simple SQL queries
```
Above link links github.com. 
This patch is to modify the link which links to https://docs.fluentbit.io/.
=> README: fix stream-processing link

installation/linux/README.md, installation/linux/amazon-linux.md, installation/linux/debian.md, installation/linux/raspbian-raspberry-pi.md, installation/linux/redhat-centos.md, installation/linux/snap.md, installation/linux/ubuntu.md, installation/supported-platforms.md
For 1.9 we have updated the GPG key to use fluentbit.io email address rather than a personal one.
This is the docs update to make it clear and should go in release note too.
=> linux: key update info

pipeline/inputs/network-io-metrics.md
This is doc PR for https://github.com/fluent/fluent-bit/pull/4995
| Key | Description | Default |
| :--- | :--- | :--- |
|test_at_init| Test the network interface is valid at initialization.| false |
=> pipeline: input: in_netif: add 'test_at_init' property

installation/linux/redhat-centos.md, installation/supported-platforms.md
=> linux: add CentOS 8 info and alternatives

installation/windows.md
Resolves: https://github.com/fluent/fluentbit-website-v3/issues/30
=> 1.9: update windows packages

pipeline/inputs/tail.md
=> pipeline: inputs: tail: add yaml samples

pipeline/filters/nightfall.md
=> pipeline: filters: nightfall: add note on missing build flag in 1.9.0

installation/linux/README.md, installation/linux/amazon-linux.md, installation/linux/debian.md, installation/linux/raspbian-raspberry-pi.md, installation/linux/redhat-centos.md, installation/linux/ubuntu.md
=> linux: update GPG keys for 1.8.15 refs

installation/docker.md
- Add the tag aliases `1.8-debug` and `1.8` only to the latest releases.
- Replace `1.9` in the docker command with `1.9.0` since the tag seems to be not there right now.
- Fix typo in the release description of `1.9.1`.
=> update docker installation page

installation/linux/ubuntu.md
In [Update your sources list](https://docs.fluentbit.io/manual/installation/linux/ubuntu#update-your-sources-lists) the package url incorrectly uses https://packages.fluentbit.io/debian/
Using the existing url returns the following error when running `sudo apt update`
`E: The repository 'https://packages.fluentbit.io/debian/focal focal Release' does not have a Release file.`
This is resolved by replacing 'debian' with 'ubuntu'.
=> installation: linux: ubuntu: fix package url for sources.list

installation/linux/redhat-centos.md
Update repo file to use releasever variable.  I believe this works, but someone should verify, please.  It works in rocky 8.
Signed-off-by: justchris1 <30219018+justchris1@users.noreply.github.com>
=> installation: linux: redhat-centos: Update repo file to use releasever variable

pipeline/filters/multiline-stacktrace.md
=> filter_multiline: add note that multiple filter definitions matching the same logs are not supported

pipeline/filters/multiline-stacktrace.md
=> filter_multiline: docker logs are split at 16KB not 32KB

pipeline/filters/lua.md
Part of https://github.com/fluent/fluent-bit/pull/5302
=> filter_lua: add inline code details

installation/linux/redhat-centos.md
Added FAQ section to RedHat install docs with a fix for 404 error on yum install from certain RedHat distros.
Signed-off-by: Adam DePollo <depolloa@uberether.com>
=> installation: linux: redhat-centos.md: Add FAQ section

pipeline/outputs/firehose.md
Signed-off-by: Matthew Fala <falamatt@amazon.com>
Compression options in Firehose supported since 1.9.0
=> kinesis_firehose: compression options documentation

pipeline/outputs/splunk.md
=> output: splunk: add http_debug_bad_request key description

pipeline/inputs/exec.md
Document the oneshot parameter (introduced in fluent/fluent-bit#2789) for version 1.7
=> pipeline: inputs: exec: document oneshot parameter (v1.7)

pipeline/inputs/exec.md
Document the `oneshot` parameter (introduced in fluent/fluent-bit#2789) for version 1.8
=> pipeline: inputs: exec: document oneshot parameter (v1.8)

pipeline/filters/checklist.md
This PR is to add below properties.
https://github.com/fluent/fluent-bit/blob/3cd0061de651db61e70573105bfff21df258355c/plugins/filter_checklist/checklist.c#L541-L556
- mode
- print_query_time
- ignore_case
=> filter_checklist: add properties.

pipeline/inputs/prometheus-scrape-metrics.md
I fixed `scrape interval`.
I think it needs underscore. `scrape_interval`.
https://github.com/fluent/fluent-bit/blob/v1.9.2/plugins/in_prometheus_scrape/prom_scrape.c#L194
=> in_prom_scrape: modify scrape_interval

pipeline/inputs/node-exporter-metrics.md, pipeline/inputs/windows-exporter-metrics.md
Config parameter of out_prometheus_exporter `listen` was deprecated in v1.9.
- https://github.com/fluent/fluent-bit/pull/4081
- https://github.com/fluent/fluent-bit-docs/pull/605
Signed-off-by: Haitao Li <hli@atlassian.com>
=> pipeline: inputs: node-expoerter-metrics: Fix parameter name in examples

stream-processing/overview.md
From: "One data is processed and it's in a safe"
To: "Once data is processed and it's in a safe"
=> Fix typo in stream processing overview

pipeline/inputs/random.md
Internal_Nsec -> Interval_Nsec
=> pipeline: inputs: random: fix typo

pipeline/filters/nest.md
pipeline: filters: nest: fix wrong numbering
Signed-off-by: slymit <slymit@gmail.com>
=> pipeline: filters: nest: fix wrong numbering

pipeline/outputs/elasticsearch.md, pipeline/outputs/opensearch.md
fixes https://github.com/fluent/fluent-bit/issues/5515
Plus smaller linting fixes in elasticsearch file
=> pipeline: output: opensearch/elasticsearch: add message regarding type parameter for opensearch 2.x as well

installation/kubernetes.md
Remove various installation methods as complex to keep all up-to-date so only reference helm.
=> kubernetes: disable non-helm

installation/windows.md
Updated checksums due to issue here: https://github.com/fluent/fluent-bit/issues/5703
=> windows: update checksums for AppVeyor builds

pipeline/inputs/dummy.md
This patch is to move configuration parameters under "Configuration Parameters" section.
https://github.com/nokute78/fluent-bit-docs/blob/in_dummy_move_conf/pipeline/inputs/dummy.md
=> pipeline: inputs: dummy: move configuration parameters

administration/configuring-fluent-bit/classic-mode/configuration-file.md
This patch adds document about the current behavior. The ordering issue is raised in https://github.com/fluent/fluent-bit/issues/5612
Signed-off-by: Haitao Li <lihaitao@gmail.com>
=> Docs about config files included using wildcard are unsorted

pipeline/inputs/exec.md
Document the oneshot parameter (introduced in fluent/fluent-bit#2789) for version 1.9+
=> pipeline: inputs: exec: document oneshot parameter (v1.9+)

pipeline/inputs/http.md
This patch is to add missing `tag_key` option.
https://github.com/fluent/fluent-bit/blob/v1.9.6/plugins/in_http/http.c#L146
| **Key**           | Description                                                                                                                                    | default |
| ----------------- | ---------------------------------------------------------------------------------------------------------------------------------------------- | ------- |
| tag_key           | Specify the key name to overwrite a tag. If set, the tag will be overwritten by a value of the key.                                            |         |
=> pipeline: input: http: add a description about tag_key

pipeline/inputs/windows-event-log-winevtlog.md
Two updates, one is the default setting for `String_Inserts` so it matches with that is in the code, the other is a subtle information about `Use_ANSI` that took me a week and reading the source code to find out.
Signed-off-by: Marcos Diez <marcos@unitron.com.br>
=> input_winevtlog: documentation updates

pipeline/inputs/kernel-logs.md
This is to add `prio_level` for in_kmsg.
https://github.com/fluent/fluent-bit/pull/5736
=> pipeline: inputs: kmsg: add prio_level option

development/golang-output-plugins.md
This patch is to add a description about configuration file setting about Golang plugin.
=> golang-output-plugin: add configuration file section

pipeline/outputs/elasticsearch.md
=> out_es: enhance descriptions of trace_error and trace_output

pipeline/filters/multiline-stacktrace.md
This patch is to revert #903 since https://github.com/fluent/fluent-bit/pull/6169 is to support multiline ruby parser.
=> pipeline: filters: multiline-stacktrace: add ruby support

installation/linux/amazon-linux.md, installation/requirements.md, installation/supported-platforms.md
Part of work for https://github.com/fluent/fluent-bit/issues/6020.
Release updates here: https://github.com/fluent/fluent-bit/pull/6186
=> linux: add AL 2022 as a supported platform

pipeline/inputs/exec.md
Resolves https://github.com/fluent/fluent-bit/issues/6236
=> exec: update to indicate not supported by containers

development/developer-guide.md
Fluent Bit 2.0 introduces cfl_list that is rebranded struct from Monkey HTTP server's mk_list.
=> developer-guide: Use cfl_list instead of mk_list

.github/actionlint-matcher.json, .github/dependabot.yml, .github/workflows/cron-stale.yaml, .github/workflows/pr-lint.yaml, .mdlrc, markdownlint.rb
MarkdownLint will only flag changed Markdown in PRs - this may mean it will flag up existing issues next time someone edits the file in a PR but ideally they are then all resolved then. I use the VSCode extension to automate this easily.
=> workflows: add basic linting and stale checks

administration/configuring-fluent-bit/classic-mode/configuration-file.md, administration/configuring-fluent-bit/yaml/configuration-file.md
`Log_Level` can be set for individual plugins the same way it can be set for the service as a whole. Is this supported? If so, could we add this to the docs like this?
=> Document configuring plugin log_level

pipeline/outputs/kinesis.md
Signed-off-by: Clay Cheng <claychen@amazon.com>
=> pipeline: outputs: kinesis: update doc for time_key_format.

administration/configuring-fluent-bit/yaml/configuration-file.md
The new syntax not includes the name property when defining inputs, outputs and filters but also does away with the single key maps that had the plugin name.
=> yaml: update syntax for 2.0.

installation/linux/debian.md
the `systemctl start` command in Debian installation is incorrect, it should be the same as [Ubuntu](https://github.com/fluent/fluent-bit-docs/blob/master/installation/linux/ubuntu.md#install-fluent-bit): `sudo systemctl start fluent-bit`
See also: https://github.com/fluent/fluent-bit-docs/commit/d0cd5b59790da4b6d5033ea7d5ae3292486bd640
I also want to point out that  `sudo service status fluent-bit` in [Ubuntu](https://github.com/fluent/fluent-bit-docs/blob/master/installation/linux/ubuntu.md#install-fluent-bit) is also wrong because the usage of  `systemctl` and `service` is different.
systemctl usage: `systemctl COMMAND SERVICE`
service usage: `service SERVICE COMMAND`
=> installation: linux: debian: fix start command

README.md, installation/getting-started-with-fluent-bit.md, installation/macos.md
Adds homebrew instructions to the macOS section of the getting started page.
While I can see that @chenrui333's homebrew this isn't an "offical" package, it's been working great for me.
I'd like to be able to recommend it to new users of fluent-bit as well.
Note: this also replaces a few remaining "MacOS" usages with the more modern "macOS" used in the majority of the documentation.
=> Macos homebrew

installation/linux/debian.md
Wrong arg order in debian docs, similar to PR https://github.com/fluent/fluent-bit-docs/pull/962
=> docs: Fix syntax error in debian installation docs

administration/configuring-fluent-bit/multiline-parsing.md
This patch is to update regex.
It was requested at https://github.com/fluent/fluent-bit-docs/pull/983#discussion_r1029929372
=> multiline-parsing: update regex

pipeline/outputs/s3.md
- prom metrics don't work (yet)
- data ordering requires a setting
- $UUID weird behavior
- different filesystem buffer size setting
=> s3: document the many ways in which S3 is special

pipeline/outputs/s3.md
My description before wasn't exactly correctly and also trying to explain why we needed to add the
preserve_data_ordering option is probably too much for end-user documentation. Better to just note
the problem and the option.
=> s3: tweak preserve_data_ordering discussion

administration/networking.md
* [ADD] add networking info
Signed-off-by: David Latorre <david@calyptia.com>
* administration: networking: add missing info
Signed-off-by: David Latorre <david@calyptia.com>
* administration: networking: add missing info
Signed-off-by: David Latorre <david@calyptia.com>
* administration: networking: add missing info
Signed-off-by: David Latorre <david@calyptia.com>
* administration: networking: add complementary info to net.dns.mode property
Signed-off-by: David Latorre <david@calyptia.com>
* administration: networking: Deleted no related http info
Signed-off-by: David Latorre <david@calyptia.com>
Signed-off-by: David Latorre <david@calyptia.com>
=> administration: networking: add missing info (#889) backport to 1.9

administration/security.md
Syslog has a TLS mode so I assume it should be on the list.
Signed-off-by: Kevin McNamee <46104536+mrkmcnamee@users.noreply.github.com>
=> Added Syslog to list of plugins that support TLS

development/developer-guide.md
Fluent-bit will provide isolated environment for development. Devcontainer is added as an alternative to Vagrant. The document about creating development environment is added and refered development guide repos.
- [Devcontainer Support PR](https://github.com/fluent/fluent-bit/pull/6880)
=> development: add development environment docs

pipeline/outputs/syslog.md
This patch is for https://github.com/fluent/fluent-bit/pull/6788
|Name|Description|Default|
|--|--|--|
|allow_longer_sd_id|If true, Fluent-bit allows SD-ID that is longer than 32 characters. Such long SD-ID violates RFC 5424.|`false`|
=> pipeline: output: syslog: add allow_longer_sd_id

SUMMARY.md, administration/hot-reload.md
Corrensponding to https://github.com/fluent/fluent-bit/pull/6871
=> hot-reload: Add docs for hot-reload

installation/macos.md, installation/windows.md
Addresses https://github.com/fluent/fluent-bit/issues/7235 by at least linking out to the default config.
Longer term we should have a matrix of supported plugins, ideally auto-generated from the cmake config.
=> windows: link out to default plugin config

pipeline/inputs/http.md
Add the new `success_header` added by https://github.com/fluent/fluent-bit/pull/6932 to the docs and gives an example about how to use.
close #1069
=> Add docs for custom headers on http input plugin

pipeline/filters/kubernetes.md
`rbac.authorization.k8s.io/v1beta1` is outdated from kubernetes v1.20
Ref: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md
> All resources within the rbac.authorization.k8s.io/v1alpha1 and rbac.authorization.k8s.io/v1beta1 API groups are deprecated in favor of rbac.authorization.k8s.io/v1, and will no longer be served in v1.20.
> https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md#deprecations-and-removals
=> Use `rbac.authorization.k8s.io/v1` in kubernetes filter doc

pipeline/inputs/podman-metrics.md
- Added image label to all container metrics in example
- Changed bytes to seconds in one of metrics (it was already done in code, docs were just not updated)
- Added new fluent-bit metrics to examples
This change reflects changes in [#7925](https://github.com/fluent/fluent-bit/pull/7295)
=> pipeline: inputs: podman metrics: Added image label to example

pipeline/filters/lua.md
`name` element should be needed to instantiate plugins.
=> filter_lua: Follow syntax change for YAML configuration

concepts/key-concepts.md, pipeline/inputs/standard-input.md
Document how to use a parser with the stdin plugin to read arbitrary messages, since the default behaviour is to assume a specific json input format. This is very confusing for new users, since the plugin just logs
invalid record found, it's not a JSON map or array
when it sees inputs it doesn't expect, and the docs don't explain that you can set a parser to handle other formats.
Document the stdin plugin's behaviour on end-of-file.
Also explain the accepted input formats for the plugin's default reader: object, object with timestamp, or object with timestamp and metadata.
=> input: stdin: Describe EoF behaviour, parser

pipeline/outputs/influxdb.md
Before merging:
1. I added header following the http output text (https://docs.fluentbit.io/manual/pipeline/outputs/http) but imo this should be later be renamed http_header for more clarity.
2.  I added the uri parameter but the description is not clear (I don't know what it does), see https://github.com/fluent/fluent-bit/blob/master/plugins/out_influxdb/influxdb.c
=> out_influxdb: remove tags_list_enabled, tags_list_keys

pipeline/parsers/logfmt.md
This documents https://github.com/fluent/fluent-bit/pull/6100
Signed-off-by: Dennis Kaarsemaker <dennis@kaarsemaker.net>
=> parser: logfmt: document logfmt_no_bare_keys

about/license.md
Fixed grammar in the initial line of "license.md" file.
=> about: license: fixed grammar in initial line

administration/configuring-fluent-bit/yaml/configuration-file.md
Backport documentation from fluent/fluent-bit-docs#1110 for version 2.0, since the change was admitted into the 2.0 release of fluent-bit, specifically in [5f50ae806d57e5277ebc476633f3ffd66bcff22b].
There are few irrelevant and superfluous changes. I will attempt to revert them later.
=> backport: improve documentation for CLIST and SLIST in yaml.

development/wasm-filter-plugins.md
This adds missing libraries required to build `flb-wamrc` when using the `-DFLB-WARMC=On` to build `fluent-bit`.
Namely `libmlir`, `libPolly`, `libedit`, and `libpfm`
See https://github.com/fluent/fluent-bit/issues/7580 for more details
=> add additional libs required to build flb-wamrc

pipeline/inputs/dummy.md
This patch is to
- Add missing `metadata` property which is supported from v2.1.0
- https://github.com/fluent/fluent-bit/commit/e4a9eec6449b582809756f99ed0b4eea30d23249#diff-259ac31effef0c86a87225f5ad013df83343367ddefb9f9c7438ef62420d676fR393
- Modify an example output.
=> in_dummy: add missing 'metadata' property

installation/docker.md, update-release-version-docs.sh
Auto-generated container installation updates were using slightly incorrect details.
Resolves https://github.com/fluent/fluent-bit-docs/issues/1130 and also duplicates part of https://github.com/fluent/fluent-bit-docs/pull/1132
=> containers: fix up version generation

pipeline/filters/parser.md
Last example on the parser.md page, shows the use of 
Reserve_Data On
Preserve_Key On
But the output had the "Reserve_Data" missing
`"key1"=>"value1", "key2"=>"value2"`
Ran local and updated the output to include **Parsed data**, **Preserve_Key(**`data`), and **Reserve_Data**(`key1`, `key2`)
=> Fix example in pipeline/filters/parser.md

pipeline/inputs/windows-exporter-metrics.md
The corresponding PR is https://github.com/fluent/fluent-bit/pull/7597.
=> in_windows_exporter_metrics: Add descriptions for service collector.

pipeline/inputs/exec.md
Document new options Exit_After_Oneshot and Propagate_Exit_Code for the related core fluent-bit PR https://github.com/fluent/fluent-bit/pull/7207
Add a security warning about shell metacharacter processing in commands.
Add an example about how to use the exec plugin as a command wrapper in one-shot mode.
=> pipeline: inputs: exec: document exit code propagation

pipeline/outputs/opensearch.md
Adding some explanation around index shards in OpenSearch domains and the kind of issues that may appear in Fluent-Bit when the domain's available shards have been used up.
=> pipeline: outputs: opensearch: Document troubleshooting for index shard availability issues

pipeline/inputs/node-exporter-metrics.md
Docs for the Systemd collector 
https://github.com/fluent/fluent-bit/pull/7319
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204737714980300
=> added systemd collector config

installation/sources/build-and-install.md
The minimum CMake version actually required to build Fluent Bit is 3.12. Looks like this was missed whenever that requirement changed.
=> update CMake version requirement

installation/sources/build-and-install.md
This (and PR #1164) bit me when trying to build on SLES12.5 which has bison 2.7-6 by default
=> Bump minimum bison version to 3

pipeline/inputs/syslog.md
This doc PR is corresponding to https://github.com/fluent/fluent-bit/pull/7651.
=> in_syslog: Add a description of source_address_key parameter

pipeline/outputs/vivo-exporter.md
Examples were missing `match` property
=> out_vivo_exporter:  Correct vivo exporter examples

pipeline/inputs/windows-exporter-metrics.md
This PR corresponds to https://github.com/fluent/fluent-bit/pull/7817.
=> in_windows_exporter_metrics: Add document for memory and paing_file metrics

pipeline/inputs/windows-exporter-metrics.md
This PR is corresponding to https://github.com/fluent/fluent-bit/pull/7860.
=> in_windows_exporter_metrics: Add document for process metrics

administration/configuring-fluent-bit/classic-mode/configuration-file.md, administration/configuring-fluent-bit/yaml/configuration-file.md
This is a doc PR for https://github.com/fluent/fluent-bit/pull/7005
|Key|Description|Default|
|--|--|--|
|sp.convert_from_str_to_num|If enabled, Stream processor converts from number string to number type.|true|
=> administration: configuration: add sp.convert_from_str_to_num

pipeline/outputs/oci-logging-analytics.md
This PR is for documentation of Oracle Cloud Infrastructure Logging Analytics output plugin.
Corresponds to https://github.com/fluent/fluent-bit/pull/7830
=> public docs for oci logging analytics

pipeline/pipeline-monitoring.md
=> pipeline: pipeline-monitoring: fix typo

pipeline/outputs/chronicle.md
Minor re-wording and typo fixes.
=> pipeline: outputs: chronicle: fix typos and make minor wording adjustments

SUMMARY.md
=> add missing link to oracle log analytics plugin

administration/configuring-fluent-bit/classic-mode/record-accessor.md, pipeline/filters/ecs-metadata.md
Removed the Limitation section from https://docs.fluentbit.io/manual/pipeline/filters/ecs-metadata#limitations-of-record_accessor-templating and added this section to https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/record-accessor
=> Record accessor limitation

administration/configuring-fluent-bit/classic-mode/record-accessor.md, pipeline/filters/ecs-metadata.md
* administration/configuring-fluent-bit/classic-mode/record-accessor adding record accessor syntax limitation
* administration/configuring-fluent-bit/classic-mode/record-accessor fixed links
* administration:configuring-fluent-bit:classic-mode:record-accessor fixed links
* administration:configuring-fluent-bit:classic-mode:record-accessor fixed links
* administration:configuring-fluent-bit:classic-mode:record-accessor fixed links
* pipeline:filters:ecs-metadata git Changed references to the record_accessor library limitation
* pipeline:filters:ecs-metadata git Changed references to the record_accessor library limitation
* pipeline:filters:ecs-metadata git Changed references to the record_accessor library limitation typos
---------
=> Record accessor limitation (Backport of #1015). 

administration/hot-reload.md
Hot reload updates to support config file option - backport of #1226
=> hot-reload: add config file option (2.1 backport)

installation/docker.md, installation/windows.md
Backport of https://github.com/fluent/fluent-bit-docs/pull/1210/
=> release: update for 2.1.10 (2.1 backport)

pipeline/filters/lua.md
This is a doc PR for https://github.com/fluent/fluent-bit/pull/7906
|Value |Description|Default|
|--|--|--|
|`enable_flb_null`|If enabled, null will be converted to flb_null in Lua. It is useful to prevent removing key/value since nil is a special value to remove key value from map in Lua.|false|
=> pipeline: filters: lua: add enable_flb_null

pipeline/filters/log_to_metrics.md
Related changes in Fluent Bit:
- https://github.com/fluent/fluent-bit/pull/7739
- https://github.com/fluent/fluent-bit/pull/7967
=> filter_log_to_metrics: Add documentation for add_label

concepts/data-pipeline/router.md
Adds documentation about `match_regex`
=> docs: add documentation about match_regex

SUMMARY.md, installation/sources/build-and-install.md
This patch is to add filter_type_converter to list.
This PR may fix https://github.com/fluent/fluent-bit-docs/issues/1103
=> summary: add type converter plugin

administration/hot-reload.md, installation/requirements.md, installation/supported-platforms.md, pipeline/inputs/exec.md, update-release-version-docs.sh
Adding doc changes as part of enabling s390x.
Related PR: https://github.com/fluent/fluent-bit/pull/8095
=> installation: platforms: add s390x to supported architectures

SUMMARY.md, installation/sources/build-and-install.md, pipeline/filters/sysinfo.md
This PR is to add a document for filter_sysinfo plugin.
https://github.com/fluent/fluent-bit/pull/8106
=> pipeline: filters: sysinfo: add document for sysinfo plugin

pipeline/filters/lua.md
Backport from (#1205) to docs 2.1
=> pipeline: filters: lua: add enable_flb_null (#1205)

stream-processing/getting-started/hands-on.md
The current [Hands On! 101](https://docs.fluentbit.io/manual/stream-processing/getting-started/hands-on) is missing the `-p read_from_head=true=` on the "4. Calculate Average Value" example. 
If you run the current example you get
```
[2023/11/24 10:40:10] [ info] [sp] registered task: flb-console:0
[2023/11/24 10:40:10] [ info] [input:tail:tail.0] inotify_fs_add(): inode=5 watch_fd=1 name=/sp-samples-1k.log
```
and not more output. There is no `{"AVG(num)"=>61.230770}`. in the output. 
By adding the `-p read_from_head=true` I get the expected output 
```
[2023/11/24 10:42:02] [ info] [sp] registered task: flb-console:0
[0] [1700822522.779461868, {"AVG(num)"=>61.230770}]
[0] [1700822522.780739544, {"AVG(num)"=>47.842106}]
[0] [1700822522.781954929, {"AVG(num)"=>40.647060}]
[0] …
```
=> Update hands-on.md to add missing -p read_from_head=true

SUMMARY.md, pipeline/inputs/process-exporter-metrics.md
Corresponding to https://github.com/fluent/fluent-bit/pull/7943.
=> in_process_exporter_metrics: Add documentation for process_exporter_metrics

pipeline/outputs/azure.md
Added documentation table prefix implementation for Azure Logs Analytics plugin.
Which is currently at PR review.
See PR: https://github.com/fluent/fluent-bit/pull/7663
See issue: https://github.com/fluent/fluent-bit/issues/7420
=> out_azure: documentation for table prefix support

pipeline/outputs/cloudwatch.md
Doc update for the following PR:
https://github.com/fluent/fluent-bit/pull/7973/files
=> cloudwatch_logs: callout support for multiple workers

pipeline/inputs/dummy.md
Documentation of new `time_interval` setting proposed in https://github.com/fluent/fluent-bit/pull/8060.
=> in_dummy: Add interval setting documentation.

installation/docker.md
Missed in #1252 for some reason.
=> docker: update for 2.2.0 release

update-release-version-docs.sh
The 2.2.0 release of Fluent Bit failed to update the container image version: #1252 
https://github.com/fluent/fluent-bit/actions/runs/6810802273/job/18519927519#step:6:22
```shell
+ MAJOR_VERSION=2.2
+ grep -q 2.2.0 /home/runner/work/fluent-bit/fluent-bit/installation/docker.md
+ echo 'Found 2.2.0 already in the Docker docs so skipping update'
Found 2.2.0 already in the Docker docs so skipping update
```
This was resolved in #1268.
The reason for the failure is `grep` using the value passed as a regex rather than a fixed literal string:
```shell
$ grep -F "2.2.0" installation/docker.md
| 2.2.0-debug | x86_64, arm64v8, arm32v7 | Debug images |
| 2.2.0 | x86_64, arm64v8, arm32v7 | Release [v2.2.0](https://fluentbit.io/announcements/v2.2.0/) |
$ grep "2.2.0" installation/docker.md
| …
```
=> scripts: fix check for container version

installation/windows.md, update-release-version-docs.sh
Resolves https://github.com/fluent/fluent-bit/issues/6937 by updating to specify the packages.fluentbit.io versions built from Github directly. These include YAML support and other improvements, the legacy AppVeyor builds are available still at releases.fluentbit.io but are deprecated.
Updated version script as well to include ARM hashes and MSI packages.
Also fixes an issue with not replacing the old version.
This needs a CI update on the Fluent Bit release process to provide the correct hashes (and for ARM too) - currently it provides the AppVeyor ones: https://github.com/fluent/fluent-bit/blob/323f343996e877c7f122d2c4e075c00c4aac7377/.github/workflows/staging-release.yaml#L882-L892
=> windows: update to use new Github builds

administration/hot-reload.md
This documentation is for an endpoint which handles for returning the hot-reloaded times.
Corresponding to https://github.com/fluent/fluent-bit/pull/7899.
=> hot_reload: Add a description for hot-reloaded count endpoint

administration/memory-management.md
"https://docs.fluentbit.io/manual/administration/memory-management"
IN the above link, when clicked on the _influxdb_ and _elasticsearch_ link, **Error 404** was shown.
=>  "pipeline: outputs: influxdb: updated influxdb and elasticsearch redirection link"

administration/buffering-and-storage.md
Fixed storage.total_limit_size misleading document content
=> Fixed storage.total_limit_size misleading document content

pipeline/inputs/kafka.md
Corresponding PR is: https://github.com/fluent/fluent-bit/pull/8174.
=> in_kafka: Add buffer_max_size description

pipeline/inputs/node-exporter-metrics.md
I checked that the new collector is already marked on the column of supported platforms.
However, the filesystem metrics is absent for now.
This PR adds the description.
=> in_node_exporter_metrics: Add a description for fileystem metrics

pipeline/inputs/kafka.md
Ref: https://github.com/fluent/fluent-bit/pull/7492
=> input: kafka: Document `data_format` option

pipeline/outputs/loki.md
I opened https://github.com/fluent/fluent-bit/issues/8348 thinking that there was no option to set uri/path for the loki output plugin, but when checking how to implement it I found out it already exists
https://github.com/fluent/fluent-bit/blob/cd497e38dc8e4e958756b449aab34801da486ad2/plugins/out_loki/loki.c#L1741-L1748
=> Added documentation for uri parameter to outputs/loki

pipeline/inputs/dummy.md
This PR documents the new `flush_on_startup` setting to the in_dummy input plugin created in https://github.com/fluent/fluent-bit/pull/8222.
=> in_dummy: Add flush_on_startup setting doc.

pipeline/inputs/kubernetes-events.md
Documentation for https://github.com/fluent/fluent-bit/pull/8323
=> in_kubernetes_events: update to match consolidated timestamp logic

pipeline/inputs/opentelemetry.md
This is a doc PR for 
https://github.com/fluent/fluent-bit/pull/8134
=> in_opentelemetry: add tag_from_uri property

pipeline/outputs/stackdriver.md
Adding this info about this issue because I lost a bunch of time trying to chase down intermittent restarts of my fluent-bit pods (v.2.2.0). 
Even if it defaults to 1 in newer versions, someone may override it, as was my case. 
Until the underlying issue is fixed, I think it's helpful to warn others about this.
=> Update stackdriver.md with warning about Workers option

pipeline/filters/record-modifier.md
This is to add examples in yaml format for record_modifier.
=> filter_record_modifier: add examples for yaml configuration

pipeline/filters/modify.md
This patch is to add examples in yaml for filter_modify.
=> filter_modify: add examples for yaml configuration

pipeline/filters/type-converter.md
This patch is to add an example in yaml for filter_type_converter.
=> filter_type_converter: add examples for yaml configuration

pipeline/inputs/node-exporter-metrics.md
This patch is to add an example in yaml for in_node_exporter_metrics .
=> in_node_exporter_metrics: add examples for yaml configuration

pipeline/outputs/prometheus-exporter.md
This patch is to add an example in yaml for out_prometheus_exporter.
=> out_prometheus_exporter: add examples for yaml configuration

pipeline/outputs/http.md
This patch is to add an example in yaml for out_http.
=> out_http: add examples for yaml configuration

pipeline/filters/rewrite-tag.md
This patch is to add an example in yaml for filter_rewrite_tag.
=> filter_rewrite_tag: add examples for yaml configuration

pipeline/filters/grep.md
This patch is to add an example in yaml for filter_grep.
=> filter_grep: add examples for yaml configuration

pipeline/inputs/forward.md
This patch is to add an example in yaml for in_forward.
=> in_forward: add examples for yaml configuration

pipeline/inputs/http.md
This patch is to add an example in yaml for in_http.
=> in_http: add examples for yaml configuration

pipeline/inputs/cpu-metrics.md
This patch is to add an example in yaml for in_cpu.
=> in_cpu: add examples for yaml configuration

pipeline/inputs/docker-metrics.md
This patch is to add an example in yaml for in_docker.
=> in_docker: add examples for yaml configuration

pipeline/inputs/docker-events.md
This patch is to add an example in yaml for in_docker_events.
=> in_docker_events: add examples for yaml configuration

pipeline/inputs/elasticsearch.md
This patch is to add an example in yaml for in_elasticsearch.
=> in_elasticsearch: add examples for yaml configuration

pipeline/inputs/fluentbit-metrics.md
This patch is to add an example in yaml for in_fluentbit_metrics.
=> in_fluentbit_metrics: add examples for yaml configuration

pipeline/inputs/kernel-logs.md
This patch is to add an example in yaml for in_kmsg.
=> in_kmsg: add examples for yaml configuration

pipeline/inputs/standard-input.md
This patch is to add an example in yaml for in_stdin.
=> in_stdin: add examples for yaml configuration

pipeline/inputs/opentelemetry.md
This patch is to add an example in yaml for in_opentelemetry.
=> in_opentelemetry: add examples for yaml configuration

README.md
Changed phrasing of line about plugins.
=> update readme.md language

pipeline/inputs/syslog.md
This patch is to add an example in yaml for in_syslog.
=> in_syslog: add examples for yaml configuration

pipeline/inputs/udp.md
This patch is to add an example in yaml for in_udp.
=> in_udp: add examples for yaml configuration

pipeline/outputs/opentelemetry.md
This patch is doc PR for https://github.com/fluent/fluent-bit/pull/8475
=> out_opentelemetry: support metadata key properties

pipeline/filters/lua.md
This patch is to add an example in yaml for filter_lua.
=> filter_lua: add examples for yaml configuration

pipeline/inputs/windows-event-log-winevtlog.md
This PR corresponds to https://github.com/fluent/fluent-bit/pull/8677.
=> in_winevtlog: Add a description for Read_Limit_Per_Cycle

pipeline/filters/kubernetes.md
Documentation for https://github.com/fluent/fluent-bit/pull/8695
=> filter_kubernetes: namespace_metadata_only doc

pipeline/inputs/tcp.md
This doc PR is corresponding to https://github.com/fluent/fluent-bit/pull/7672.
=> in_tcp: Add a description for source_address_key

pipeline/inputs/forward.md
To work as secure forward connection, there are a few parameters to be needed to specify:
* shared_key
* self_hostname
* security.users
Corresponding to https://github.com/fluent/fluent-bit/pull/8665.
=> in_forward: Add descrioptions for secure forward related parameters

SUMMARY.md, installation/buildroot-embedded-linux.md, installation/getting-started-with-fluent-bit.md
Code:
https://gitlab.com/buildroot.org/buildroot/-/tree/master/package/fluent-bit
Supported version:
https://release-monitoring.org/project/267335
```
buildroot$ ./utils/test-pkg -p fluent-bit -a
arm-aarch64 [ 1/42]: OK
bootlin-aarch64-glibc [ 2/42]: OK
bootlin-arcle-hs38-uclibc [ 3/42]: OK
bootlin-armv5-uclibc [ 4/42]: OK
bootlin-armv7-glibc [ 5/42]: OK
bootlin-armv7m-uclibc [ 6/42]: SKIPPED
bootlin-armv7-musl [ 7/42]: OK
bootlin-m68k-5208-uclibc [ 8/42]: SKIPPED
bootlin-m68k-68040-uclibc [ 9/42]: OK
bootlin-microblazeel-uclibc [10/42]: OK
bootlin-mipsel32r6-glibc [11/42]: OK
bootlin-mipsel-uclibc [12/42]: OK
bootlin-nios2-glibc [13/42]: OK
bootlin-openrisc-uclibc [14/42]: OK
bootlin-powerpc64le-power8-glibc [15/42]: OK
bootlin-powerpc-e500mc-uclibc [16/42]: OK
bootlin-riscv32-glibc …
```
=> installation: add buildroot-embedded-linux.md

installation/linux/ubuntu.md
This clarifies the version information for ubuntu which is outdated since the release of Ubuntu 24.04.
See also https://github.com/fluent/fluent-bit/issues/8775.
=> Clearer version information for Ubuntu

installation/macos.md
This is because recent GHA's macos-latest is replaced with Apple Silicon based worker.
We don't need to mention Apple Silicon restriction.
=> installation: macos: Remove Apple silicon restrictions

.gitbook.yaml, SUMMARY.md, pipeline/outputs/azure_kusto.md
Microsoft Fabric Real Time Analytics is a SAAS offering in Microsoft Fabric while Azure Kusto is a PAAS offering in Azure. Microsoft Fabric Real Time Analytics has eventhouse(Kusto) for data storage. Hence we are using the same output plugin we have for Azure Kusto to send log data to Microsoft Fabric Real Time Analytics.
For more details please refer to the following documentations
https://learn.microsoft.com/en-us/fabric/real-time-analytics/overview
https://learn.microsoft.com/en-us/fabric/real-time-analytics/realtime-analytics-compare
=> added links for Microsoft Fabric Real Time Analytics

installation/windows.md
Fix link loop by clicking on the download page link, which redirects you to the same page.
=> Fix windows.md installer link loop "from the download page."

installation/kubernetes.md, pipeline/filters/kubernetes.md
Removing incorrect usage of old style CRI parser that just confused people and creates problems.
Resolved various other niggles.
=> Update K8S installation to remove legacy cri info

SUMMARY.md, administration/transport-security.md, pipeline/inputs/prometheus-remote-write.md
Corresponding to https://github.com/fluent/fluent-bit/pull/8725.
=> in_prometheus_remote_write: Add documentation for input plugin of prometheus remote write

pipeline/outputs/loki.md
In code it's actually "fluent-bit" not "fluentbit" as documented: https://github.com/fluent/fluent-bit/blob/master/plugins/out_loki/loki.c#L454
=> Fix default labels value for Loki

pipeline/outputs/kafka.md
This is similar to the log_key in other outputs, e.g. the cloudwatch one.
=> pipelines: outputs: kafka: Document the raw_log_key

pipeline/parsers/configuring-parser.md
This PR adds documentation for the proposed `Time_System_Timezone` configuration option.
Related PR: https://github.com/fluent/fluent-bit/pull/8164
=> Add Time_System_Timezone parser option docs

administration/transport-security.md, pipeline/filters/kubernetes.md
Corresponding to https://github.com/fluent/fluent-bit/pull/8966.
=> tls: Add descriptions for x509v3 alt name verification (tls.verify_hostname)

pipeline/inputs/opentelemetry.md
Previously this table only included the different HTTP1 input types.
=> Update OpenTelemetry input docs to be more clear about GRPC support

pipeline/inputs/tail.md
YAML examples in the `tail` input plugin are invalid, and produce an error `section 'input' is missing the 'name' property`, which a colleague of mine got tripped up on.
This PR fixes.
=> pipeline/inputs/tail: fix YAML examples

pipeline/inputs/exec-wasi.md, pipeline/inputs/exec.md
- as-is: https://docs.fluentbit.io/manual/configuration/unit_sizes
- to-be: `(../../administration/configuring-fluent-bit/unit-sizes.md)` (https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/unit-sizes)
=> Fix unit sizes docs link

pipeline/inputs/kubernetes-events.md
All entries in under sections(ex. SERVICE, INPUT, ...) must be indented, 4 spaces ideally.
=> pipeline: inputs: kubernetes-events: Add indent in example config

pipeline/outputs/gelf.md
Corresponding to https://github.com/fluent/fluent-bit/pull/9031
=> out_gelf: Add Gelf_Tag_Key description

pipeline/processors/metrics-selector.md
Corresponding to https://github.com/fluent/fluent-bit/pull/8812
=> processor_label_value: Add label parameter description and add example configuration for delete_label_value operation

pipeline/inputs/kubernetes-events.md
Documentation for fluent/fluent-bit#8351
=> in_kubernetes_events: add k8s permission details

pipeline/inputs/exec-wasi.md
- remove typo x, in Wasm_Stack_Size
- Add closing parenthesis, in Buf_Size
=> pipeline: inputs: exec-wasi: Fix broken links

concepts/data-pipeline/buffer.md
I enabled a setting within the GitBook UI (not GitHub) to resolve [this issue](https://github.com/fluent/fluent-bit-docs/issues/1433), but it looks like the changes won't go into effect until the docs site gets built again. this is a trivial update to force the docs site to rebuild :)
=> Trivial update to force GitBook refresh

concepts/data-pipeline/buffer.md, concepts/data-pipeline/filter.md, concepts/data-pipeline/input.md, concepts/data-pipeline/output.md, concepts/data-pipeline/parser.md, concepts/data-pipeline/router.md
following up on https://github.com/fluent/fluent-bit-docs/pull/1438 and https://github.com/fluent/fluent-bit-docs/issues/1433: it turns out GitBook doesn't rebuild all pages after a PR, only the pages that were actually changed in the PR. so this is me changing all of the pages with Mermaid diagrams to get GitBook to rebuild those pages, which should (hopefully) in turn fix the Mermaid diagrams on those pages 😅
=> Trivial updates to force GitBook refresh (again)

pipeline/inputs/forward.md
Fix a small typo in user key definition in Forward protocol input.
=> Typo in secure forward key

SUMMARY.md, administration/multithreading.md
this PR adds a doc about multithreading capabilities in Fluent Bit.
(it's still on my to-do list to (1) update the relevant input docs with info about threading and (2) update the relevant output docs with info about workers)
=> Add multithreading doc

pipeline/filters/kubernetes.md, pipeline/filters/lua.md, pipeline/inputs/opentelemetry.md, pipeline/inputs/prometheus-remote-write.md, pipeline/outputs/chronicle.md, pipeline/outputs/oci-logging-analytics.md, pipeline/outputs/s3.md, pipeline/outputs/vivo-exporter.md, pipeline/outputs/websocket.md
- Reindent fluent-bit (classic) configuration file example with 4 spaces
- Entries under section must be indented, 4 spaces ideally ([docs](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/format-schema#sections))
- You don't necessarily need to make it 4 spaces (any same indent level in single section is OK -just like python), but many people copy the example code from the documentation and try to use it, so IMO it's better to make it ideal.
- Add empty line between sections in config file
- Add syntax highlight for yaml (` ```yml`)
- Remove 'Line separator(U+2028)' character from vivo-exporter
=> Reindent configuration file example, improve readability, etc.

administration/monitoring.md
This PR updates the [Fluent Bit monitoring page](https://docs.fluentbit.io/manual/administration/monitoring) for style and consistency with Chronosphere guidelines.
=> [docs][sc-105732] Update the Fluent Bit monitoring page

about/fluentd-and-fluent-bit.md
Standardizing this page for style.
Note: Line 36 was confusing to me. I rewrote it to something that makes sense, but I'm also not completely sure I'm correct.
=> Cleanup for about fluentbit and fluentd

pipeline/outputs/cloudwatch.md
Changes:
- New section: "Integration with Localstack (CloudWatch Logs)" added under the configuration file section.
-    Configuration parameters for Localstack (endpoint and port).
-    Instructions for exporting AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY as local variables for testing.
This update ensures that users working with Localstack can easily configure and test CloudWatch Logs output with Fluent Bit.
=> add to cloudwatch readme, supports for localstack

SUMMARY.md, pipeline/outputs/openobserve.md
Description:
This PR adds OpenObserve (O2) as a supported output destination for Fluent Bit, allowing users to forward logs seamlessly to O2. The integration works without any code or implementation changes, as Fluent Bit's existing configuration system can handle the output forwarding.
Context:
There isn't an open issue for this feature, but adding OpenObserve as an output destination can provide users with an efficient logging solution. Since no code modifications are necessary, this update can be applied without concerns.
=> adding openobserve for 3.1

administration/configuring-fluent-bit/README.md, vale-styles/FluentBit/Ampersand.yml
Updating the config Fluent Bit page for style.
Also fixing a test that was incorrect.
=> Docs: Updating config file for style

pipeline/filters/record-modifier.md
Updates the record-modifier plugin page for consistent grammar and style.
=> docs: pipeline: Updating record-modifier for style

pipeline/outputs/elasticsearch.md, vale-styles/FluentBit/Spelling-exceptions.txt
=> pipelines: docs: bringing elasticsearch up to standards

pipeline/inputs/tail.md
This change clarifies the sequential parser application process and provides a concrete example for better understanding.
=> Clarified parser behavior in documentation

concepts/data-pipeline/output.md
Basic style updates for consistency.
=> concepts: output: style updates

concepts/data-pipeline/parser.md
Applying style for consistency.
=> concepts: parsers: update page for style

concepts/data-pipeline/filter.md
Implement general stylistic updates to page for consistency.
=> concepts: filter: update for style

concepts/data-pipeline/input.md
Implement general stylistic updates to page for consistency.
=> Fluentbit: docs: Update input concept for style

SUMMARY.md, pipeline/outputs/dynatrace.md
This commit introduces a new page for Dynatrace output based on http plugin.
It provides sample configuration and recommended steps and additional resources to enable Fluent Bit output for Dynatrace http endpoint.
=> Dynatrace guide for http plugin

administration/multithreading.md, vale-styles/FluentBit/Spelling-exceptions.txt
Minor stylistic updates for the Multithreading doc.
=> multithreading: minor style updates

administration/networking.md, vale-styles/FluentBit/Spelling-exceptions.txt
Signed-off-by: Lynette Miles <lynette.miles@chronosphere.io>Signed-off-by: Lynette Miles <lynette.miles@chronosphere.io>
Updating the admin > networking page for style and consistency.
=> admin: networking: updating for style

pipeline/outputs/datadog.md
Added docs for custom Datadog output custom HTTP headers
=> out_datadog: custom http headers

pipeline/outputs/influxdb.md
Corresponding to https://github.com/fluent/fluent-bit/pull/9301.
=> out_influxdb: Add a description for Add_Integer_Suffix parameter

pipeline/outputs/kinesis.md
This commit introduces a new 'port' configuration option for the Kinesis output plugin. This enhancement allows users to specify a custom TCP port for connecting to the Kinesis Streams service, providing greater flexibility in network configurations.
Key changes:
- Added 'port' option to the configuration documentation
- Updated the Kinesis output plugin to support custom port connections
- Maintained default behavior (port 443) when no custom port is specified
This feature is particularly useful in environments where non-standard ports are required due to network policies or when connecting through proxies that use alternative ports.
The change is backwards compatible, as existing configurations without a specified port will continue to use the default port 443.
=> pipeline: outputs: kinesis: add custom port configuration option

pipeline/inputs/docker-metrics.md
**What type of PR is this?**
documentation
**What does this PR do / Why do we need it?**:
At times the user might need to have their docker [Daemon data directory](https://docs.docker.com/engine/daemon/#daemon-data-directory) setup somewhere else other than the default path. Currently the **Docker Log Based Metrics** plugin does not pick it up automatically and has it [hard coded here](https://github.com/fluent/fluent-bit/blob/a15cc2060ae7cc6404360c5c50665bab29cfe9ab/plugins/in_docker/docker.h#L33C9-L33C32). 
We can simply pass `path.containers` to the config and that will do the trick as the plugin code is also looking at that same [config here](https://github.com/fluent/fluent-bit/blob/a15cc2060ae7cc6404360c5c50665bab29cfe9ab/plugins/in_docker/docker.c#L572)
This can significantly save …
=> pipeline: inputs: docker-metrics: add container path config

installation/aws-container.md
=> Updating for style

SUMMARY.md, administration/transport-security.md, pipeline/outputs/dash0.md, pipeline/outputs/elasticsearch.md, pipeline/outputs/gelf.md, pipeline/outputs/http.md, pipeline/outputs/influxdb.md, pipeline/outputs/kafka-rest-proxy.md, pipeline/outputs/oci-logging-analytics.md, pipeline/outputs/opensearch.md, pipeline/outputs/skywalking.md, pipeline/outputs/splunk.md, pipeline/outputs/syslog.md, vale-styles/FluentBit/Spelling-exceptions.txt
Added documentation on how to send logs to dash0 based on the OpenTelemetry output plugin.
=> pipeline: outputs: dash0: Added Dash0 documentation

pipeline/outputs/dash0.md
when updating the docs we lost the placeholder for the auth token
=> pipeline: outputs: dash0: replace auth token with placeholder

pipeline/outputs/dash0.md
The macro for the code toggle tabs cannot be indented under the list
=> pipeline: outputs: dash0: fix code toggle

pipeline/parsers/configuring-parser.md
Hi I'm just a passer-by that spotted a typo while perusing the docs.
=> fix small typo in configuring-parser.md

pipeline/inputs/statsd.md
I added this doc for already implement metrics parameter for in_statsd plugin.
This was implemented in v3.1.6 and here is the PR: https://github.com/fluent/fluent-bit/pull/9119
=> in_statsd: Add a description for Metrics parameter

administration/transport-security.md
=> Updating transport security for style and grammar

administration/configuring-fluent-bit/yaml/parsers-section.md
The link does not work. I've found a suitable page, so I've updated the link.
=> Fix broken link in parsers-section.md

pipeline/filters/parser.md
Documentation for PR https://github.com/fluent/fluent-bit/pull/9828
=> pipelines: filters: parser: Add a nest_under parameter

pipeline/filters/parser.md
Reverts fluent/fluent-bit-docs#1543 until the related engineering PR is merged.
=> Revert "pipelines: filters: parser: Add a nest_under parameter"

pipeline/filters/kubernetes.md
Querying owner references via kubernetes filter is merged in https://github.com/fluent/fluent-bit/pull/9719.
=> Update kubernetes filter documentation with the usage of Owner_References.

installation/upgrade-notes.md
Reverts fluent/fluent-bit-docs#1580 after reverting and regenerating the underlying release: https://github.com/fluent/fluent-bit/issues/10042#issuecomment-2700449580
=> upgrade: revert info about release info changes

pipeline/outputs/stackdriver.md, pipeline/outputs/stackdriver_special_fields.md
The special fields documentation as it existed was a bit of a mishmash of old documentation for a previous logging agent solution and a lot of additions over the years trying to match the old format. It ends up reproducing a lot of information that is better stated by the existing Cloud Logging docs, while missing crucial details about how the plugin handled these cases. Certain fields were also missing.
This PR rewrites the documentation, doing more linking out to Google Cloud Logging documentation in place of rewording the same information. It also guides more generally on some of the edge cases for how the special fields are handled, calling out the exceptions in a clearer way. It also adds some fields that were previously missing from this document.
=> stackdriver: Refactor special fields docs

pipeline/inputs/opentelemetry.md
Resolves failure seen in https://github.com/fluent/fluent-bit/issues/9391 due to missing docs.
=> inputs: opentelemetry: add clarification to tag and tag_from_uri

pipeline/inputs/windows-event-log-winevtlog.md
Added documentation for "ignore_missing_channels" in WinevtLogs input.
=> IN:WinevtLogs - added documentation for "ignore_missing_channels"

pipeline/inputs/tail.md
Added missing YAML configuration examples for TAIL input plugin in that docs page.
=> Added YAML configuration examples for tail input plugin docs.

pipeline/outputs/loki.md
Adds docs for PR https://github.com/fluent/fluent-bit/pull/9530
=> loki_out: add structured_metadata_map docs

administration/configuring-fluent-bit/yaml/service-section.md
Small update to service configuration docs adding hot_reload to the options list and example usage at the bottom in yaml configuration.
=> Added hot_reload to service section yaml configuration with example.

administration/hot-reload.md
Adding hot_reload example to a YAML tab in the Hot Reload page.
=> Updated hot reload page with yaml example in tab form.

pipeline/processors/README.md, pipeline/processors/conditional-processing.md
this adds a few changes to the conditional processing PR that was merged yesterday.
https://github.com/fluent/fluent-bit-docs/pull/1598
=> Conditional processing doc fixes

installation/windows.md
As `C:\Program Files\fluent-bit\` is the default install location for fluent-bit it makes sense that the documentation supports this.
The current work-around doesn't make sense when it can easily be resolved by simply escaping the quotation marks.
This should give new users a better experience as the documentation follows a default installation.
Feel free to remove/ignore the -Description commit, I just think it gives a more concise and proper look inline with how most Windows services look and feel.
=> installation: windows: Fix Service creation C:\Program Files via PowerShell

SUMMARY.md, pipeline/processors/README.md, pipeline/processors/filters.md
Fixes https://github.com/fluent/fluent-bit-docs/issues/1604
=> Document filters as processors 

CONTRIBUTING.md, local-testing/logging-pipeline.md, local-testing/validating-your-data-and-structure.md
a few of the links I updated in my last couple PRs broke... turns out the guidance in CONTRIBUTING.md doesn't quite work. (yay gitbook.) updated that to a hopefully more reliable guideline.
=> Fix a few links + update link guidance in CONTRIBUTING.md

README.md
Gitbook has decided to do bad things with line breaks, so we're having to make the page code less readable to make the actual doc more readable.
=> Attempting to fix what gitbook made a mess of

stream-processing/getting-started/fluent-bit-sql.md
cleanups for style, clarity, and consistency.
=> stream-processing: getting-started: fluent-bit-sql: general cleanup

pipeline/inputs/nginx.md, vale-styles/FluentBit/EnDash.yml
PR removes endashes and turns the enDash Vale test to error.
=> Vale: removing dashes and turning on test

CONTRIBUTING.md, SUMMARY.md, administration/buffering-and-storage.md, pipeline/inputs/cpu-metrics.md, vale-styles/FluentBit/Ampersand.yml
Updates the ampersand test for vale and sets it at a warning level. Also made a couple of changes to test it, and added the test's info to the contributing file.
=> Vale: Ampersand test and testing

CONTRIBUTING.md, vale-styles/FluentBit/AmSpelling.yml
Adds the AmSpelling vale test at error level.
=> Vale: Add US spelling test

CONTRIBUTING.md, pipeline/outputs/azure_kusto.md, vale-styles/FluentBit/LyHyphens.yml
Updates the LyHyphens test to error level, fixes the single instance of error, and adds the test info to the contribution file.
=> Vale: Set LyHyphens to error

CONTRIBUTING.md, pipeline/filters/throttle.md, pipeline/inputs/process-exporter-metrics.md, vale-styles/FluentBit/Ordinal.yml
This changes the Ordinal vale test to error, corrects the files with issues, and updates the contributing file with the test info.
=> Vale: Set Ordinal test to error, fix problems

CONTRIBUTING.md, administration/configuring-fluent-bit/yaml/configuration-file.md, vale-styles/FluentBit/HeadingPunctuation.yml
Sets the vale HeadingPunctuation test to error, corrects the one instance where this was a problem, and adds the test info to the contributions file.
=> Vale: Add HeadingPunctuation test to error

development/library_api.md
=> development: library-api: general cleanup

CONTRIBUTING.md, vale-styles/FluentBit/Gender.yml, vale-styles/FluentBit/GenderBias.yml
This PR sets the Gender and GenderBias Vale tests to error.
=> Changing GenderBias and Gender tests to error

installation/linux/raspbian-raspberry-pi.md
Update instructions to include Raspbian Bookworm (12).
Reference [fluent-bit/issues/8786](https://github.com/fluent/fluent-bit/issues/8786)
=> installation: update instructions to include Raspbian Bookworm (12)

administration/configuring-fluent-bit/yaml/service-section.md
=> Style: service section update

administration/configuring-fluent-bit/yaml/includes-section.md
Updates the selected page to meet basic style guidelines.
=> Admin:config:yaml:includes Style updates

administration/configuring-fluent-bit/yaml/multiline-parsers-section.md, vale-styles/FluentBit/Spelling-exceptions.txt
Updates the selected page to meet style guidelines.
=> Admin:config:yaml:multiline parsers Style updates

administration/configuring-fluent-bit/classic-mode/variables.md
Updates the selected page for style guidelines.
=> Classic mode variables: Style update

administration/configuring-fluent-bit/classic-mode/upstream-servers.md
Updates the selected page for style guidelines.
=> Classic-upstream: style updates

development/wasm-filter-plugins.md, vale-styles/FluentBit/Acronyms.yml, vale-styles/FluentBit/Spelling-exceptions.txt
=> development: wasm-filter: general cleanup

administration/configuring-fluent-bit/classic-mode/format-schema.md
updating to match style guidelines.
=> Admin: config: classic: scema: Update for style

development/developer-guide.md, vale-styles/FluentBit/Acronyms.yml
=> development: developer-guide: general cleanup

administration/configuring-fluent-bit/unit-sizes.md
=> Admin: config: unit size: style updates

development/ingest-records-manually.md
update the selected page for style.
=> Dev: manual ingest style update

development/golang-output-plugins.md
Update seleceted page for style.
=> Dev: golang: Style updates

pipeline/outputs/azure_blob.md
Adding documentation for missing options: `compress` and `compress_blob` in Azure Blob Plugin.
Corresponding source code reference to these options in branch `v4.0.0`:
`compress`: https://github.com/fluent/fluent-bit/blob/v4.0.0/plugins/out_azure_blob/azure_blob.c#L1175
`compress_blob`: https://github.com/fluent/fluent-bit/blob/v4.0.0/plugins/out_azure_blob/azure_blob.c#L1181
Issue and discussion reference:
https://github.com/fluent/fluent-bit/issues/10140
=> pipeline: outputs: azure_blob: Add compress and compress_blob options

pipeline/filters/ecs-metadata.md, vale-styles/FluentBit/Acronyms.yml
=> Pipeline: filters: ecs-metadata: update for style

pipeline/filters/aws-metadata.md
=> Pipeline:filters:metadata: updating for style

pipeline/filters/expect.md
=> Pipeline: filters: expect: Style updates

pipeline/filters/checklist.md
=> Pipeline: plugins: checklist: update for style

pipeline/filters/grep.md
=> Pipeline: filters: grep: update for style

pipeline/filters/geoip2-filter.md
=> Pipeline: filter: geoip style update

pipeline/filters/kubernetes.md, vale-styles/FluentBit/Spelling-exceptions.txt
Update kubernetes filter page for style
=> Kubernetes filter for style

pipeline/inputs/tail.md, vale-styles/FluentBit/Spelling-exceptions.txt
this PR adds info about using inotify to monitor a large number of files, which I'm told has been a supported feature for a while but was never added to the docs.
=> pipeline: inputs: tail: add inotify info

pipeline/filters/modify.md
Updates the selected page for consistent style.
=> Pipeline: filters: modify: style updates

pipeline/filters/nightfall.md
Updates the page for stylistic consistency.
=> Pipeline: filters: nightfall: style updates

administration/buffering-and-storage.md
This PR douments the new storage config option `storage.backlog.flush_on_shutfown`. When enabled, Fluent Bit will attempt to flush all backlog filesystem chunks to their destination(s) during the shutdown process. This can help ensure data delivery before fluent bit stops, but may increase shutdown time.
Default value is off.
See corresponding fluent-bit PR: https://github.com/fluent/fluent-bit/pull/9952
=> administration: add storage.backlog.flush_on_shutfown option

installation/docker.md
Hello! 
I was testing Fluent Bit earlier this week, and struggled with getting the new YAML configuration file to work with Docker. 
Just mounting the volume doesn't work, the default `fluent-bit.conf` in the image takes precedence over the YAML file, which took me a while to troubleshoot. 
For example:
```yaml
pipeline:
inputs:
- name: dummy
dummy: '{"from": "yaml"}'
outputs:
- name: stdout
```
Running `docker run -ti -v ./fluent-bit.yaml:/fluent-bit/etc/fluent-bit.yaml cr.fluentbit.io/fluent/fluent-bit` does not load the YAML file. 
Mounting the .conf file works though.
Maybe this will help those who tried the same thing as I did.
Let me know if you think anything needs changing or if you believe there is a better way to do this. Thanks!
=> Docker: how to use a configuration file

pipeline/filters/parser.md
=> Pipeline: filters: parser: Style updates

administration/aws-credentials.md
Adds the documentation for the new pod identity credential used for AWS plugins: https://github.com/fluent/fluent-bit/pull/10114
=> aws-credentials: update credential page with pod identity information

pipeline/filters/nest.md
Updates page for stylistic consistency.
=> Pipeline: filters: nest: style updates

pipeline/filters/type-converter.md
Updates for style and consistency.
=> Pipeline: filters: type-converter: style

pipeline/filters/sysinfo.md, vale-styles/FluentBit/Spelling-exceptions.txt
Update for style and consistency.
=> Pipeline: filters: sysinfo: Style

pipeline/filters/rewrite-tag.md
Update for style and consistency.
=> pipeline: filters: rewrite_tag: Style

pipeline/filters/lua.md
=> pipeline: filters: lua: general cleanup

pipeline/inputs/disk-io-metrics.md
=> pipeline: inputs: disk: style

pipeline/inputs/dummy.md
update for style and consistency.
=> plugin: input: dummy: style:

pipeline/inputs/docker-metrics.md
=> pipeline: input: docker-metrics: style

pipeline/inputs/docker-events.md
=> Pipeline: input: docker-events: style

pipeline/inputs/exec-wasi.md, vale-styles/FluentBit/Acronyms.yml
Updating for style. Some capitalization is still inconsistent because it's not clear what ones are correct and deep diving into acronym/abbreviation spelling and correctness is out of scope.
=> Pipeline: input: wasi-exec: style

pipeline/inputs/forward.md
=> pipeline: inputs: forward: style

pipeline/inputs/health.md
Updating for style and consistency.
=> pipeline: input: health: style

pipeline/inputs/kernel-logs.md
=> pipeline: input: kernel: style

pipeline/inputs/kafka.md, vale-styles/FluentBit/Spelling-exceptions.txt
=> Pipeline:input:kafka: style

installation/kubernetes.md
Added YAML configuration to kubernetes installation docs. Fixes #1737.
=> Added YAML configuration to kubernetes installation docs. Fixes #1737.

administration/scheduling-and-retries.md
Added YAML examples to scheduling and retries doc. Fixes #1742.
=> Added YAML examples to scheduling and retries doc. Fixes #1742.

administration/networking.md
Added YAML examples to the networking docs. Fixes #1744.
=> Added YAML examples to the networking docs. Fixes #1744.

administration/monitoring.md
Adding YAML examples, three of them, to monitoring docs. Fixes #1746.
=> Adding YAML examples to monitoring docs. Fixes #1746.

pipeline/outputs/elasticsearch.md
Adding YAML examples to elastic search output plugin docs. Fixes #1723.
=> Adding YAML examples to elastic search output plugin docs. Fixes #1723.

administration/transport-security.md
Adding YAML examples to administration transport security docs. Fixes #1759.
=> Adding YAML examples to administration transport security docs. Fixes #1759.

local-testing/logging-pipeline.md
Adding YAML examples to local testing logging pipeline docs. Fixes #1766.
=> Adding YAML examples to local testing logging pipeline docs. Fixes #1766.

pipeline/inputs/kubernetes-events.md
=> Pipeline: input: kubernetes: style

pipeline/inputs/mqtt.md, vale-styles/FluentBit/Acronyms.yml
=> Pipeline: inputs: mqtt: style

pipeline/inputs/memory-metrics.md
=> Pipeline: input: memory: style

pipeline/inputs/opentelemetry.md
=> Pipeline: inputs: otlp: style

pipeline/inputs/podman-metrics.md, vale-styles/FluentBit/Spelling-exceptions.txt
=> Pipeline: inputs: podman: style

development/wasm-filter-plugins.md
Adding YAML examples to developers wasm filter plugin docs. Fixes #1768.
=> Adding YAML examples to developers wasm filter plugin docs. Fixes #1768.

pipeline/inputs/exec-wasi.md
Adding YAML examples to input plugin exec-wasi doc. Fixes #1780.
=> Adding YAML examples to input plugin exec-wasi doc. Fixes #1780.

pipeline/inputs/ebpf.md
Adding YAML examples to input plugin ebpf docs. Fixes #1782.
=> Adding YAML examples to input plugin ebpf docs. Fixes #1782.

administration/monitoring.md
Fixing issues with monitoring docs page. Fixes #1784.
=> Fixing issues with monitoring docs page. Fixes #1784.

pipeline/inputs/disk-io-metrics.md
Fixing layout order and standardizing disk io metrics docs. Fixes #1788.
- shell usage for commands
- text formatting for classic configs
- order of YAML config first in tabs
=> Fixing layout order and standardizing disk io metrics docs. Fixes #1788.

pipeline/inputs/dummy.md
Fixes to shell usage and standardized on Yaml configuration. Fixes #1794.
=> Fixes to shell usage and standardized on Yaml configuration. Fixes #1794.

pipeline/inputs/elasticsearch.md
Standardized on yaml and fixed shell usage for Elasticsearch input plugin docs. Fixes #1796.
=> Standardized on yaml and fixed shell usage for Elasticsearch input plugin docs. Fixes #1796.

pipeline/inputs/windows-event-log-winevtlog.md
Small commit to add the YAML version of the config file that is used on many other document pages.
=> inputs: winevtlog: Adding yaml version of config

pipeline/inputs/health.md
Updated health input plugin docs to standardize on YAML and shell usage. Fixes #1807.
=> Updated health input plugin docs to standardize on YAML and shell usage. Fixes #1807.

pipeline/inputs/head.md
Fixes for YAML defaults and shell usage. Fixes #1805.
=> Fixes for YAML defaults and shell usage. Fixes #1805.

pipeline/inputs/kernel-logs.md
Fixing shell commands, standardizing YAML first in kernel logs docs. Fixes #1813.
=> Fixing shell commands, standardizing YAML first in kernel logs docs. Fixes #1813.

pipeline/inputs/kafka.md
Adding YAML examples and fixing shell layouts for kafka input plugin docs. Fixes #1811.
=> Adding YAML examples and fixing shell layouts for kafka input plugin docs. Fixes #1811.

pipeline/inputs/kubernetes-events.md
Adding YAML examples for k8s events input plugin docs. Fixes #1815.
=> Adding YAML examples for k8s events input plugin docs. Fixes #1815.

pipeline/inputs/mqtt.md
Adding YAML examples and standardizing shell commands. Fixes #1819.
=> Adding YAML examples and standardizing shell commands. Fixes #1819.

pipeline/inputs/statsd.md
=> Pipeline: input: statsd: style

pipeline/inputs/syslog.md
This has a couple of markdownlint errors due to repeated headers. These are fixable, but would require rewriting the procedures in a heavier effort than this cleanup is supposed to take on.
=> Pipeline: input: syslog: style

pipeline/processors/conditional-processing.md
The [Conditional Processing](https://docs.fluentbit.io/manual/pipeline/processors/conditional-processing) feature does not work with [Filter as Processor](https://docs.fluentbit.io/manual/pipeline/processors/filters). This is not clearly mentioned in the documentation, which can be confusing for users who expect conditional rules to apply to [Filters](https://docs.fluentbit.io/manual/pipeline/filters) like [Lua](https://docs.fluentbit.io/manual/pipeline/filters/lua) and [Modify](https://docs.fluentbit.io/manual/pipeline/filters/modify) when used as processors.
I reported this limitation in the [fluent-bit GitHub repo](https://github.com/fluent/fluent-bit/issues/10524), including configuration examples and steps to reproduce the issue. Until this feature is supported, the documentation …
=> pipeline: add note to explicit the limitation of conditional processing by using filter as processor

pipeline/inputs/node-exporter-metrics.md
Fixing shell usage and standardizing on YAML examples for node exporter metrics input plugin. Fixes #1831.
=> Fixing shell usage and standardizing on YAML examples for node exporter metrics input plugin. Fixes #1831.

pipeline/inputs/network-io-metrics.md
Fixing shell usage and standardizing on YAML examples for network io metrics input plugin. Fixes #1829.
=> Fixing shell usage and standardizing on YAML examples for network io metrics input plugin. Fixes #1829.

pipeline/inputs/process-exporter-metrics.md
Adding YAML examples and shell standardization to process exporter metrics input plugin docs. Fixes #1847.
=> Adding YAML examples and shell standardization to process exporter metrics input plugin docs. Fixes #1847.

pipeline/inputs/random.md
Fixing shell usage and YAML config for random input plugin docs. Fixes #1854.
=> Fixing shell usage and YAML config for random input plugin docs. Fixes #1854.

pipeline/inputs/prometheus-remote-write.md
Adding YAML examples and standardizing shell usage for prom remote write input plugin docs. Fixes #1853.
=> Adding YAML examples and standardizing shell usage for prom remote write input plugin docs. Fixes #1853.

pipeline/inputs/process.md
Adding YAML examples and standardizing shell usage for Process Log Based Metrics. Fixes #1852.
=> Adding YAML examples and standardizing shell usage for Process Log Based Metrics. Fixes #1852.

pipeline/inputs/process.md, pipeline/inputs/prometheus-remote-write.md, pipeline/inputs/random.md
=> pipeline: inputs: random: general cleanup

pipeline/parsers/configuring-parser.md, pipeline/parsers/decoders.md, pipeline/parsers/json.md, pipeline/parsers/logfmt.md, pipeline/parsers/ltsv.md, pipeline/parsers/regular-expression.md
Missing YAML examples for parsers docs. Fixes #1865.
- [Configuring parser doc](https://docs.fluentbit.io/manual/pipeline/parsers/configuring-parser)
- [Regular expression doc](https://docs.fluentbit.io/manual/pipeline/parsers/regular-expression)
- [Logfmt doc](https://docs.fluentbit.io/manual/pipeline/parsers/logfmt)
- [JSON doc](https://docs.fluentbit.io/manual/pipeline/parsers/json)
- [LTSV doc](https://docs.fluentbit.io/manual/pipeline/parsers/ltsv)
- [Decoders doc](https://docs.fluentbit.io/manual/pipeline/parsers/decoders)
=> Missing YAML examples for parsers docs. Fixes #1865.

pipeline/inputs/windows-event-log-winevtlog.md
As far as I can find it was the only place where it's spelled like this
=> sqllite typo in windows-event-log-winevtlog example config

pipeline/parsers/decoders.md
Fixing missing close tab code for parsers decoders doc. Part of issue #1865.
Just added closing tab and end tab code.
=> Fixing missing close tab code for parsers decoders doc. Part of issue #1865.

administration/configuring-fluent-bit/multiline-parsing.md
Fixing error in YAML examples for multiline parsing yaml doc.
Was missing a rule attribute.
=> Fixing error in YAML examples for multiline parsing yaml doc.

pipeline/filters/aws-metadata.md, pipeline/filters/ecs-metadata.md, pipeline/filters/geoip2-filter.md, pipeline/filters/kubernetes.md, pipeline/filters/lua.md, pipeline/filters/multiline-stacktrace.md, pipeline/filters/nightfall.md, pipeline/filters/record-modifier.md, pipeline/filters/standard-output.md, pipeline/filters/tensorflow.md, pipeline/filters/throttle.md
Update the filter docs with YAML configuration examples, the first half of filters in list. Fixes #1872.
Updated the following:
- [AWS Metadata](https://docs.fluentbit.io/manual/pipeline/filters/aws-metadata)
- [ECS Metadata](https://docs.fluentbit.io/manual/pipeline/filters/ecs-metadata)
- [GeoIP2 Filter](https://docs.fluentbit.io/manual/pipeline/filters/geoip2-filter)
- [Kubernetes](https://docs.fluentbit.io/manual/pipeline/filters/kubernetes)
- [Lua](https://docs.fluentbit.io/manual/pipeline/filters/lua)
- [Record Modifier](https://docs.fluentbit.io/manual/pipeline/filters/record-modifier)
- [Multiline](https://docs.fluentbit.io/manual/pipeline/filters/multiline-stacktrace)
- [Nightfall](https://docs.fluentbit.io/manual/pipeline/filters/nightfall)
- [Standard …
=> Update the filter docs with YAML configuration examples, the first half of filters in list. Fixes #1872.

pipeline/filters/aws-metadata.md, pipeline/filters/ecs-metadata.md, pipeline/filters/geoip2-filter.md, pipeline/filters/kubernetes.md, pipeline/filters/lua.md, pipeline/filters/multiline-stacktrace.md, pipeline/filters/nightfall.md, pipeline/filters/record-modifier.md, pipeline/filters/standard-output.md, pipeline/filters/tensorflow.md, pipeline/filters/throttle.md
Reverts fluent/fluent-bit-docs#1875 
nevermind, I'll just make a new PR that fixes the issues.
=> Revert "Revert "Update the filter docs with YAML configuration examples, the first half of filters in list. Fixes #1872.""

pipeline/parsers/ltsv.md, vale-styles/FluentBit/Acronyms.yml
=> pipeline: parsers: lstv: general cleanup

pipeline/parsers/logfmt.md, vale-styles/FluentBit/Spelling-exceptions.txt
=> pipeline: parsers: logfmt: general cleanup

pipeline/processors/README.md
=> pipeline: processors: README: general cleanup

pipeline/processors/README.md, pipeline/processors/filters.md
=> pipeline: processors: filters: general cleanup

pipeline/outputs/azure_kusto.md, vale-styles/FluentBit/Acronyms.yml, vale-styles/FluentBit/Spelling-exceptions.txt
Updating selected page for style and consistency. Also updating a couple of vale tests for spelling and acronyms.
=> Pipeline: output: kusto: style

CONTRIBUTING.md, vale-styles/FluentBit/Acronyms.yml
Adding some more info about what tests we're running, so contributors know what we're looking for and how to get the testing software to run locally for themselves.
=> contributing: more info on tests

pipeline/outputs/cloudwatch.md, pipeline/outputs/firehose.md, pipeline/outputs/kinesis.md, pipeline/outputs/s3.md
Adjusted amazon outputs code examples to use 2 space indentations; Amazon Cloudwatch, Amazon Kinesis Data Firehose, Amazon Kinesis Data Streams, and Amazon S3.
=> Adjusted amazon outputs code examples to use 2 space indentations. Fixes #1890. 

pipeline/outputs/counter.md, pipeline/outputs/dash0.md, pipeline/outputs/datadog.md, pipeline/outputs/dynatrace.md
Update the [output plugin docs](https://docs.fluentbit.io/manual/pipeline/outputs) with YAML configuration examples for Counter, DashO, Datadog, and Dynatrace.
=> Added YAML examples for the output plugins listed in description. Fixes #1899.

vale-styles/FluentBit/Hints.yml
this PR adds a vale suggestion to use GitBook hints rather than ` > Note: lorem ipsum`.
=> add vale rule to use gitbook hint syntax

pipeline/outputs/kafka.md, pipeline/outputs/loki.md
The construct below had missing first bracket, so fixed for Loki and Kafka docs to get tabs working:
`{% tabs %}`
=> Fixes to broken tab constructs on Loki and Kafka output docs. Part of issue 1916.

pipeline/outputs/azure_logs_ingestion.md, vale-styles/FluentBit/Headings.yml
=> Pipeline: output: azure logs: style

pipeline/outputs/counter.md
=> Pipeline: output: counter: style

pipeline/outputs/nats.md, pipeline/outputs/postgresql.md, pipeline/outputs/prometheus-exporter.md, pipeline/outputs/prometheus-remote-write.md, pipeline/outputs/skywalking.md, pipeline/outputs/slack.md, pipeline/outputs/splunk.md, pipeline/outputs/stackdriver.md, pipeline/outputs/stackdriver_special_fields.md, pipeline/outputs/standard-output.md, pipeline/outputs/syslog.md, pipeline/outputs/tcp-and-tls.md, pipeline/outputs/treasure-data.md, pipeline/outputs/vivo-exporter.md, pipeline/outputs/websocket.md
Update the [output plugin docs](https://docs.fluentbit.io/manual/pipeline/outputs) with YAML configuration examples for the following:
- NATS
- PostgreSQL
- Prometheus Exporter
- Prometheus Remote Write
- SkyWalking
- Slack
- Splunk
- Stackdriver
- Standard Output
- Syslog
- TCP and TLS
- Treasure Data
- Vivo Exporter
- WebSocket
Fixes #1941.
=> Missing YAML examples for the remaining output plugins. Fixes #1941.

pipeline/outputs/forward.md, vale-styles/FluentBit/Headings.yml
=> Pipeline: output: forward: style

pipeline/outputs/flowcounter.md, vale-styles/FluentBit/Headings.yml
=> Pipeline: output: flowcounter: style

pipeline/outputs/file.md, vale-styles/FluentBit/Headings.yml
=> Pipeline: output: file: style

pipeline/outputs/elasticsearch.md, vale-styles/FluentBit/Headings.yml, vale-styles/FluentBit/Spelling-exceptions.txt
unfixing line breaks mostly due to gitbook.
=> Pipeline: output: elasticsearch: style

pipeline/processors/sql.md, vale-styles/FluentBit/Headings.yml
=> pipeline: processors: sql: general cleanup

pipeline/processors/metrics-selector.md
=> pipeline: processors: metrics-selector: general cleanup

pipeline/outputs/kafka.md, vale-styles/FluentBit/Acronyms.yml, vale-styles/FluentBit/Headings.yml, vale-styles/FluentBit/Spelling-exceptions.txt
=> Pipeline: output: kafka producer: style

pipeline/parsers/configuring-parser.md, pipeline/parsers/decoders.md, pipeline/parsers/json.md, pipeline/parsers/logfmt.md, pipeline/parsers/ltsv.md, pipeline/parsers/regular-expression.md
All the[ parser examples](https://docs.fluentbit.io/manual/pipeline/parsers) currently have 4 space indentation, standardizing on 2 space indentations. Fixes #1967.
=> Indentation for Parsers section code examples in docs need to be 2 space standardized. Fixes #1967.

pipeline/outputs/postgresql.md, pipeline/outputs/prometheus-exporter.md, vale-styles/FluentBit/Headings.yml, vale-styles/FluentBit/Spelling-exceptions.txt
=> Pipeline: output: posgresql: style

pipeline/outputs/prometheus-exporter.md
=> Pipeline: output: prom exporter: style

pipeline/outputs/prometheus-remote-write.md, vale-styles/FluentBit/Headings.yml
=> Pipeline: output: prom remote write: style

pipeline/outputs/splunk.md
=> pipeline: output: splunk: style

pipeline/outputs/null.md
=> pipeline: outputs: null: general cleanup

pipeline/outputs/oci-logging-analytics.md, vale-styles/FluentBit/Headings.yml
=> pipeline: outputs: oci: general cleanup

pipeline/outputs/tcp-and-tls.md, vale-styles/FluentBit/Headings.yml
=> pipeline: output: tls tcp: style:

pipeline/outputs/treasure-data.md, vale-styles/FluentBit/Headings.yml
=> pipeline: output: treasure data: style:

pipeline/outputs/syslog.md
=> pipeline: outputs: syslog: general cleanup

vale-styles/FluentBit/FluentBitCasing.yml
This adds a test to check for Fluent Bit - properly spaced and capitalized.
It *mostly* works. I can't get it to not flag on markdown links  like `[fluent-bit-4.0.4-win32.msi]`
But this should catch most of them.
=> Vale: Fluent Bit casing test

about/sandbox-and-lab-resources.md
Fixing broken EKS workshop link in about page. Fixes #2005.
=> Fixing broken EKS workshop link in about page. Fixes #2005.

administration/backpressure.md, administration/buffering-and-storage.md, administration/configuring-fluent-bit/multiline-parsing.md, administration/memory-management.md, administration/monitoring.md, administration/networking.md, administration/scheduling-and-retries.md, administration/transport-security.md, administration/troubleshooting.md
Fixing admin docs, standardization of coding examples. Fixes #2007.
=> Fixing admin docs, standardization of coding examples. Fixes #2007.

about/fluentd-and-fluent-bit.md, about/sandbox-and-lab-resources.md, vale-styles/FluentBit/Headings.yml, vale-styles/FluentBit/Spelling-exceptions.txt
Some more minor changes for vale/markdownlint
remaining suggestions are due to bare urls or markup required by gitbook.
=> About: fluent bit and fluentd: final style

administration/configuring-fluent-bit/classic-mode/configuration-file.md, administration/configuring-fluent-bit/classic-mode/format-schema.md, administration/configuring-fluent-bit/classic-mode/upstream-servers.md, administration/configuring-fluent-bit/classic-mode/variables.md, administration/configuring-fluent-bit/multiline-parsing.md, administration/configuring-fluent-bit/yaml/environment-variables-section.md, administration/networking.md, administration/transport-security.md, development/golang-output-plugins.md, development/msgpack-format.md, installation/aws-container.md, installation/linux/alma-rocky.md, installation/linux/amazon-linux.md, installation/linux/debian.md, installation/linux/raspbian-raspberry-pi.md, installation/linux/redhat-centos.md, installation/linux/ubuntu.md, installation/macos.md, installation/sources/build-and-install.md, installation/sources/build-with-static-configuration.md, installation/sources/download-source-code.md, installation/upgrade-notes.md, installation/windows.md, local-testing/logging-pipeline.md, pipeline/inputs/exec.md, pipeline/inputs/standard-input.md, stream-processing/getting-started/hands-on.md
General code example cleanup where wrong code type specified in code blocks throughout entire docs project. Fixes #2020.
Looking to standardize and searching out incorrect usage of shell vs bash and text vs python.
=> General code example cleanup where wrong code type specified in code blocks throughout entire docs project. Fixes #2020.

installation/aws-container.md, installation/buildroot-embedded-linux.md, installation/docker.md, installation/getting-started-with-fluent-bit.md, installation/kubernetes.md, installation/linux/alma-rocky.md, installation/linux/amazon-linux.md, installation/linux/debian.md, installation/linux/redhat-centos.md, installation/linux/ubuntu.md, installation/macos.md, installation/sources/build-and-install.md, installation/sources/build-with-static-configuration.md, installation/upgrade-notes.md, installation/windows.md, installation/yocto-embedded-linux.md, vale-styles/FluentBit/Acronyms.yml, vale-styles/FluentBit/Headings.yml, vale-styles/FluentBit/Spelling-exceptions.txt
=> Install: final vale test pass

.github/workflows/pr-lint.yaml, CONTRIBUTING.md, installation/getting-started-with-fluent-bit.md
This adds vale testing as a GitHub action. Vale will run on any updated text in PRs and display notices in the Files Changed tab. Vale tests are set to fail on [tests that error](https://github.com/fluent/fluent-bit-docs/blob/master/CONTRIBUTING.md#additional-testing). Failing tests do not block merging at this time.
=> Testing CI/CD by adding vale to actions

pipeline/outputs/oci-logging-analytics.md
This pull request updates the documentation for the Oracle Cloud Infrastructure Logging Analytics output plugin to reflect recent service name change at OCI from Logging Analytics to Log Analytics. The plugin name itself is not being changed to not introduce any breaking changes.
=> Update Log Analytics plugin docs for OCI service rename

pipeline/inputs/prometheus-textfile.md, vale-styles/FluentBit/Spelling-exceptions.txt
Corrects multiple stylistic issues introduced in the previous PR.
=> Correcting multiple stylistic issues created in #2036

installation/linux/debian.md
This pull request corrects a typo in the documentation for installing Fluent Bit on `Debian` systems. The package name has been updated to the correct `fluent-bit`
=> installation: linux: debian: update package name to fluent-bit

.github/workflows/linkcheck.yaml
This updates the link checker test to run on Sundays at 6 PM and open an issue if there's a bad link.
If this does open an issue on sunday (because I know there's one link that does complain due to a 403), then we'll know it works. 
Once it's working, I'll follow up with a secondary issue to run the link checker once a month so we can be sure the links are being checked regularly, without overwhelming the issue queue.
=> Link checker scheduling

.github/workflows/linkcheck.yaml
This PR changes the link check test to run on the first of the month at 1800 hours. This ensures we have at least a once a month check on links.
Also adds notes on how to use the checker for PRs when you're moving pages around so you don't get a bunch of link report issues.
=> Update Linkcheck test frequency

administration/monitoring.md
:wave:
While working on reducing dropped logs in a high-volume Kubernetes setup, we found the ingestion paused input metric (added in https://github.com/fluent/fluent-bit/pull/8044) to be super helpful for validating Fluent Bit health under pressure and for tuning settings like `mem_buf_limit`. We realized it was not called out in the docs, so this PR adds it to the metrics reference for future operators.
=> Add fluentbit_input_ingestion_paused metric to the documentation

pipeline/parsers/configuring-parser.md
On the "Configuring parsers" section, subsection "Parser Configuration File"[2], it says:
> All parsers must be defined in a parsers file, not in the Fluent Bit
> global configuration file.
But on the "Parsers" page[1] for the v4.0 documentation, it states:
> You can define parsers either directly in the main configuration file
> or in separate external files for better organization.
Those seem like contradictory statements. I think the truth is that parsers may be defined in the main global configuration file if the main configuration file is YAML, or in a separate "parsers" file in either classic or YAML config files. I think the behavior of supporting parsers defined in the main YAML configuration file has been supported since v3.2
I'm proposing the smallest possible change to make the …
=> fix: Parsers do not have to be in seperate files

pipeline/outputs/cloudwatch.md
Without this policy it won't be possible to use custom retention period
=> Update CloudWatch plugin's required IAM permissions

installation/downloads/linux.md, installation/downloads/linux/alma-rocky.md, installation/downloads/linux/amazon-linux.md, installation/downloads/linux/debian.md, installation/downloads/linux/raspbian-raspberry-pi.md, installation/downloads/linux/redhat-centos.md, installation/downloads/linux/ubuntu.md
This abstracts some duplicated info out of some of the installation files and crosslinks rather than duplicates.
=> intallation: Abstracting duplicated info

pipeline/outputs/opentelemetry.md
Looks like the last `endtabs` encoding was different in the output plugin docs file for OTel,  copied over from working markdown doc files seems to change that line. Also fixed 4 space tabs in classic config as rest of the examples are standardized on 2 spaces.
Fixes #2073.
=> Looks like the last endtabs encoding was different than other working markdown doc files. Fixes #2073.

SUMMARY.md, administration/configuring-fluent-bit/classic-mode.md, administration/configuring-fluent-bit/yaml.md
Turns the "readme" file into a real page for classic config mode and rewords the yaml config page a little based on a suggestion from #2096
=> Config: classic mode: adding index page
