- getting_started/configuration_file.md
- input/forward.md
- input/serial.md
- input/stdin.md
- input/xbee.md
- installation/build_install.md
- output/elasticsearch.md
- output/forward.md
- output/stdout.md
I fixed typos and updated execution result using newest fluent-bit.
(I want to update out_nats result, but I can't test it...)
> Doc: fix typo and update execution result

- input/health.md
I updated document of in_health to explain new options add_host and add_port.
> in_health:add explanation of add_host and add_port

- SUMMARY.md
- input/README.md
- input/proc.md
I added a documentation about a plugin in_proc.
> Add a documentation about in_proc

- SUMMARY.md
- output/README.md
- output/flowcounter.md
I added a documentation about out_flowcounter.
> output: new FlowCounter output documentation

- SUMMARY.md
- input/README.md
- input/disk.md
I added a documentation about in_disk.
> in_disk: add new documentation about in_disk

- configuration/file.md
I added a explanation about filter plugin to document about configuration file.
> configuration: add a description about filter

- input/mem.md
I updated a documentation about in_mem.
I added example of this feature.
https://github.com/fluent/fluent-bit/pull/164
> in_mem:update example and add information about swap

- SUMMARY.md
- output/README.md
- output/file.md
I added a documentation about out_file.
> output: file: add documentation for out_file

- output/file.md
I added a document about ltsv format.
See also https://github.com/fluent/fluent-bit/pull/255
> out_file: add description about ltsv format

- SUMMARY.md
- output/README.md
- output/null.md
I added a documentation about out_null plugin.
> out_null: add document about out_null

- input/head.md
I added explanation about https://github.com/fluent/fluent-bit/pull/300
> in_head: add option 'key'

- SUMMARY.md
- input/README.md
- input/dummy.md
I added a documentation about in_dummy.
> in_dummy: add new documentation about in_dummy

- SUMMARY.md
- input/README.md
- input/netif.md
I added a document about in_netif.
> input: add in_netif document

- filter/parser.md
To follow https://github.com/fluent/fluent-bit/pull/336
> filter_parser: add explanation about 'reserve_data'

- about/README.md
- about/fluentd_and_fluentbit.md
Fixes some grammar and spelling errors.
> Small corrects to documents in about section

- parser/README.md
I added description about the feature https://github.com/fluent/fluent-bit/pull/398 (parser: support hexadecimal format)
> parser: add hex format to types option

- configuration/schema.md
> Fix typo in configuration schema

- SUMMARY.md
- input/README.md
- input/exec.md
I added a document about in_exec plugin.
> input: exec: add a document about in_exec

- output/influxdb.md
Signed-off-by: Vetési Zoltán <vetesi.zoltan@gmail.com>
> output: influxdb: document new Auto_Tag and Tag_Keys options

- installation/kubernetes.md
Signed-off-by: hiroshi <hiroshi3110@gmail.com>
> fix a typo

- configuration/memory_usage.md
> Correct English language tense.

- output/azure.md
> output: azure: fix typo

- configuration/file.md
I added an explanation about wildcard to include multiple files.
https://github.com/fluent/fluent-bit/issues/556
https://github.com/monkey/monkey/pull/282
> configuation: file: support wildcard to include files

- configuration/backpressure.md
> fix typos in backpressure

- filter/modify.md
This adds new documentation for the added rules and conditions in fluent-bit PR  https://github.com/fluent/fluent-bit/pull/618
> filter_modify: Add new rules and conditions

- output/elasticsearch.md
+ some minor changes just to make text more consistent
Signed-off-by: Konstantin K Kornienko <konstantin_kornienko@epam.com>
> add 'Replace_Dots' param for elastic to docs

- output/kafka.md
This resolves fluent/fluent-bit#707
> Document setting librdkafka properties

- filter/lua.md
I added an description about type_int_key of filter_lua.
see also https://github.com/fluent/fluent-bit/pull/727
> filter_lua: add new property type_int_key

- parser/README.md
small typo: i**n**portant -> i**m**portant
> parser: readme: fix typo

- configuration/file.md
> Add `Match_Regex` documentation

- output/elasticsearch.md
- Trace_Output
- Current_Time_Index
- Logstash_Prefix_Key
> [out/elasticsearch] Add documentation around missing fields

- filter/kubernetes.md
Document [#440](https://github.com/fluent/fluent-bit/pull/440).
> Add Annotations config

- output/elasticsearch.md
Fixes https://github.com/fluent/fluent-bit/issues/900.
Signed-off-by: Alexander Kabakaev <kabakaev@gmail.com>
> output: elasticsearch: add the Path key.

- filter/parser.md
Document option `Preserve_Key`, and improve documentation for `Reserve_Data`.
> Update parser.md on preserving fields

- input/systemd.md
Maybe merge it after https://github.com/fluent/fluent-bit/pull/904
> [in_systemd] document strip_underscores parameter

- filter/kubernetes.md
Document `Merge_Log_Trim`, `Annotations` and `Dummy_Meta` for `0.14` branch.
> filter: kubernetes: add missing params

- filter/kubernetes.md
> filter: kubernetes: add Merge_Log_Trim default value

- output/elasticsearch.md
> out: elasticsearch: add missing fields

- filter/lua.md
> filter: lua: fix markdown formatting

- output/splunk.md
> out: splunk: Fix #132

- input/systemd.md
> input: systemd: Add missing fields

- SUMMARY.md
- development/golang_plugins.md
This is the initial post for documenting the development of golang plugins
Signed-off-by: Warren Fernandes <wfernandes@pivotal.io>
> development: golang_plugins: add documentation for golang plugins

- input/cpu.md
Signed-off-by: Mohammad Nasirifar <farnasirim@gmail.com>
> input: cpu: document interval_[n]sec params

- filter/grep.md
> filter: grep: add example for nested fields

- output/README.md
I added TCP & TLS plugin to output plugin list.
> output: add TCP plugin to plugin list

- output/stackdriver.md
See relevant code here:
https://github.com/fluent/fluent-bit/blame/master/plugins/out_stackdriver/stackdriver.c#L384
> Update supported resource types in the docs

- SUMMARY.md
- input/README.md
- input/collectd.md
Add a documentation to explain all the configurable parameters
of the new plugin and show the basic usage of it.
This is a supplement patch to fluent/fluent-bit/pull/1506
> input: collectd: document the new collectd plugin

- SUMMARY.md
- configuration/tls_ssl.md
- output/gelf.md
Just added a fully descriptive documentation for GELF output plugin. I tried to include everything I saw in implementation. Hope this helps.
> add gelf output plugin documentation

- input/tail.md
Based on the comment: 
https://github.com/fluent/fluent-bit/issues/716#issuecomment-414460134
> Ignore_Older is record based

- configuration/file.md
I believe this has changed sometime in the past, but the docs weren't updated.
> Update WITH_TRACE build option reference to FLB_TRACE

- output/datadog.md
* Add `compress` option setting
* Fix default TLS setting to `off`
PR related to: https://github.com/fluent/fluent-bit/pull/1772
> [out_datadog] Add `compress` option

- installation/upgrade_notes.md
"is not longer necessary" -> "is no longer necessary"
> installation: upgrade notes: fix grammar

- output/elasticsearch.md
Current documentation is unclear/incomplete - updated to explain how the Logstash_Prefix_Key configuration works.
> Update ES plugin readme for Logstash_Prefix_Key

- pipeline/outputs/pgsql.md
Added the first documentation for pgsql output plugin
> output: pgsql: Added the first documentation for pgsql output plugin

- concepts/data-pipeline/filter.md
- concepts/data-pipeline/input.md
- concepts/data-pipeline/output.md
- concepts/data-pipeline/parser.md
These links are currently broken on the documentation website.
My guess is these are the correct links. 
Thanks
> Fix broken documentation link

- pipeline/filters/lua.md
I added a description about return code 2.
| return code | description |
|---------------|-------------|
|-1 | drop the record |
|0 | keep the original |
|1| replace timestamp and record |
|2(new)|keep the original timestamp and replace record|
https://github.com/fluent/fluent-bit/pull/2100
> pipeline: filter: lua: add description about code 2

- pipeline/inputs/forward.md
To fix #284 
I copied from https://github.com/fluent/fluent-bit-docs/blob/7049e9e805cfc8fe2cf7dad5b2d84fe127aa090d/input/forward.md and fix broken links.
> restore in_forward.md

- development/developer-guide.md
- development/library_api.md
I fixed broken links on development document.
> Fix links of development docs

- pipeline/filters/lua.md
https://github.com/fluent/fluent-bit/pull/2100 is released and supported from v1.4.3.
https://fluentbit.io/announcements/v1.4.3/
I added supported version of the feature.
> pipeline: filter: lua: add supported version of return code 2

- pipeline/outputs/kafka.md
the commit add description of dynamic_topic option in out_kafka
Signed-off-by: Michael Voelker <novecento@gmx.de>
> out_kafka: add dynamic_topic

- pipeline/outputs/elasticsearch.md
> Update link to tls section

- pipeline/filters/kubernetes.md
I added two options to mitigate unstable DNS issues on Windows.
Both will be available on Fluent Bit v1.5.
> Document "DNS_Retries" and "DNS_Wait_Time" options

- pipeline/outputs/forward.md
See https://github.com/fluent/fluent-bit/pull/2266 for accompanying code.
> pipeline: output: forward: document tag_rewrite option

- pipeline/outputs/postgresql.md
Signed-off-by: Gabriele Bartolini <gabriele.bartolini@2ndQuadrant.it>
> Review documentation for the PostgreSQL output plugin

- pipeline/outputs/stackdriver.md
Adding new supported resource types: k8s_container, k8s_node and k8s_pod
Signed-off-by: Jeff Luo <jeffluoo@google.com>
> out_stackdriver: Add new k8s resource types

- pipeline/outputs/postgresql.md
Added documentation for options async, min_pool_size and max_pool_size
Signed-off-by: Jonathan Gonzalez V <jonathan.gonzalez@2ndquadrant.com>
> output: postgres: options async, min_pool_size and max_pool_size

- pipeline/inputs/docker_events.md
Documentation for docker_events plugin. PR: https://github.com/fluent/fluent-bit/pull/2216
> pipeline: inputs: docker_events: Initial checkin of documentation

- pipeline/inputs/dummy.md
This is a patch for https://github.com/fluent/fluent-bit/pull/2107
> pipeline: inputs: dummy: add new property 'Start_time_*sec'

- pipeline/outputs/elasticsearch.md
> out_es: docs for full Amazon ElasticSearch Service support

- stream-processing/README.md
- stream-processing/introduction.md
- stream-processing/stream-processing.md
Just a typo fix.
Signed-off-by: David Calvert <davidcalvertfr@gmail.com>
> Fixed minor typo in stream-processing documentation

- pipeline/outputs/stackdriver.md
- pipeline/outputs/stackdriver_special_fields.md
Signed-off-by: Jeff Luo <jeffluoo@google.com>
> out_stackdriver: Add documentation for labels_key

- pipeline/outputs/stackdriver.md
- pipeline/outputs/stackdriver_special_fields.md
Add document for special fields of stackdriver output plugin.
Signed-off-by: scgao <scgao@google.com>
> out_stackdriver: Document for special fields

- pipeline/outputs/elasticsearch.md
Add documentation for new option added in fluent/fluent-bit#2544
> out_es: Document Time_Key_Nanos option

- pipeline/outputs/postgresql.md
Added documentation for new option
> output: pgsql: Added documentation for new option `cockroachdb`

- pipeline/filters/aws-metadata.md
added default value to metadata fields list
Signed-off-by: Drew Zhang <zhayuzhu@amazon.com>
> filters: aws metadata: added default value to metadata fields list

- .gitbook.yaml
- SUMMARY.md
- administration/security.md
- installation/sources/build-and-install.md
- pipeline/outputs/s3.md
> out_s3: add documentation

- .gitbook.yaml
- SUMMARY.md
- administration/security.md
- installation/sources/build-and-install.md
- pipeline/outputs/firehose.md
> out_kinesis_firehose: add docs

- pipeline/outputs/cloudwatch.md
- pipeline/outputs/elasticsearch.md
Signed-off-by: Meghna Prabhu <meghnapr@amazon.com>
> aws: Add documentation for sts endpoint in ES and CW plugins

- pipeline/filters/tensorflow.md
Signed-off-by: Masoud Koleini <masoud.koleini@arm.com>
> filter_tensorflow: add documentation for Tensorflow filter plugin

- SUMMARY.md
Signed-off-by: Masoud Koleini <masoud.koleini@arm.com>
> filter_tensorflow: add Tensorflow to the list of filters in SUMMARY.md

- pipeline/outputs/stackdriver.md
This configuration parameter is currently undocumented.
> out_stackdriver: Update configuration parameters with severity_key

- pipeline/filters/kubernetes.md
- pipeline/inputs/tail.md
Some fixes I found while referring to the docs
> Fix links in tail and kubernetes doc pages

- pipeline/inputs/memory-metrics.md
It simply adds the table with the params accepted in the conf file.
[Interval_Sec](https://github.com/fluent/fluent-bit/blob/317937e358457990be9426aa5ab137c53860251e/plugins/in_mem/mem.c#L139)
[PID](https://github.com/fluent/fluent-bit/blob/317937e358457990be9426aa5ab137c53860251e/plugins/in_mem/mem.c#L149)
> pipeline: input: memory: add configuration parameters

- pipeline/outputs/s3.md
> out_s3: fix reliability section, add use_put_object

- administration/networking.md
This is the corresponding documentation for fluent/fluent-bit#2704
> network: Add information about `net.keepalive_max_recycle`

- pipeline/outputs/forward.md
See corresponding PR https://github.com/fluent/fluent-bit/pull/2773
> pipeline: output: forward: document compress option

- about/fluentd-and-fluent-bit.md
I was reading the docs and found that some of them didn't read as well as they could. The changes are simple - just wording, nothing about the concepts or content itself is wrong. Hope this helps
> changed wording for better smoothness / flow

- .gitbook.yaml
- SUMMARY.md
- installation/sources/build-and-install.md
- pipeline/inputs/docker.md
Signed-off-by: championshuttler <shivams2799@gmail.com>
cc @edsiper
> Add docker input plugin docs

- pipeline/inputs/forward.md
Attempt to
Fixes #343 
Signed-off-by: championshuttler <shivams2799@gmail.com>
> Fix the docs for forward input plugin

- stream-processing/README.md
Signed-off-by: championshuttler <shivams2799@gmail.com>
cc @edsiper
> Fix the link to the stream processor image

- pipeline/inputs/syslog.md
Add UPD to Listen and Port keywords
> Add UPD to Listen and Port

- administration/configuring-fluent-bit/configuration-file.md
> Fix typos in configuration-file.md

- SUMMARY.md
- pipeline/outputs/websocket.md
this is first PR to add document for out_websocket plugin
> out_websocket: add documentation 

- pipeline/filters/kubernetes.md
https://github.com/fluent/fluent-bit/pull/2481
> Add documentation for use_docker_id

- pipeline/inputs/exec.md
- pipeline/inputs/tail.md
Fixes https://github.com/fluent/fluent-bit-docs/issues/356
> Issue #356: Fixed broken links to Unit Size specification

- pipeline/inputs/tail.md
This PR is related to fluent-bit PR https://github.com/fluent/fluent-bit/pull/3038
Signed-off-by: Yong Tang <yong.tang.github@outlook.com>
> Update docs for tail plugin (add Offset_Key)

- pipeline/outputs/websocket.md
[out_websocket] doc change with PR #3010
> [out_websocket] doc change with PR #3010

- SUMMARY.md
- administration/http-proxy.md
Signed-off-by: Sanya Kochhar <kochhars@microsoft.com>
> administration: update http proxy doc for clarity and visibility

- pipeline/outputs/s3.md
> out_s3:fix wrong tag delimiters in the example

- pipeline/outputs/s3.md
> out_s3: add docs for canned ACL, content options and ECR Public

- pipeline/outputs/stackdriver.md
Relates to fluent/fluent-bit#3106 
Relates to fluent/fluent-bit#3113
> out_stackdriver: added export_to_project_id field

- installation/kubernetes.md
> Fix K8s Doc Typo

- pipeline/outputs/elasticsearch.md
Added Informarion about key "Trace_Error"
Signed-off-by: Ilya Fedotov Ilya.v.fedotov@gmail.com
> Add missing documentation for Elasticsearch plugin

- .gitbook.yaml
- SUMMARY.md
- administration/security.md
- installation/sources/build-and-install.md
- pipeline/outputs/kinesis.md
> out_kinesis_streams: add docs

- pipeline/outputs/influxdb.md
documentation changes for https://github.com/fluent/fluent-bit/pull/3040
> out_influxdb: support v2

- pipeline/outputs/elasticsearch.md
I added a description about `suppress_type_name`.
ref: https://github.com/fluent/fluent-bit/pull/3140
> outputs: elasticsearch: add option suppress_type_name

- pipeline/outputs/s3.md
> out_s3: add slash in the example s3_key_format

- pipeline/inputs/tail.md
Use of a more explicit term as the title says
> tail: change Tag_Regex "file" term to more explicit "file name" term

- stream-processing/changelog.md
Fix link
https://docs.fluentbit.io/manual/stream-processing/changelog
```
For more details please review the section Check Keys and NULL values
```
> stream-processing: fix broken link

- pipeline/outputs/s3.md
This reverts commit 0b6bdaf145b46651cb346cb10a1c7a5170785c8f.
> out_s3: revert docs update for s3_key_format enhancements

- pipeline/filters/record-modifier.md
Ref: https://github.com/fluent/fluent-bit/pull/3179
- Add description about Allowlist_key option
- replace whitelist with allowlist
> filters: record_modifier: use bias-free words.

- pipeline/outputs/elasticsearch.md
I added option `id_key`.
The option is added by https://github.com/fluent/fluent-bit/pull/3320
> outputs: elasticsearch: add property 'id_key'

- pipeline/outputs/s3.md
This reverts commit 2b163c5e8af614429d4fe2c7fe3db9509a88329e.
> out_s3: add docs for s3_key_format enhancement as 1.7.3 is released

- administration/backpressure.md
Hi! I found some broken link at [Backpressure](https://docs.fluentbit.io/manual/administration/backpressure) page.
Please check link.
Have a nice day 😃
> backpressure: fix broken link 'Tail Input'

- pipeline/outputs/s3.md
Docs related to fluent/fluent-bit#3333
Signed-off-by: Steve McKay <steve.mckay@signifyd.com>
> out_s3: docs for send_content_md5

- pipeline/outputs/http.md
See https://github.com/fluent/fluent-bit/pull/3348
> document the newly added log_response_payload parameter

- pipeline/parsers/regular-expression.md
Signed-off-by: Sanya Kochhar <kochhars@microsoft.com>
> parsers_regex: fix broken links

- pipeline/filters/kubernetes.md
> filter: kubernetes: add docs for kube_meta_cache_ttl(#3623)

- administration/monitoring.md
Signed-off-by: Drew Zhang <zhayuzhu@amazon.com>
> http_server: add document for health check endpoint

- pipeline/filters/kubernetes.md
> filter: kubernetes: add docs for kube_token_command(#3677)

- pipeline/inputs/tail.md
Resolves https://github.com/fluent/fluent-bit-docs/issues/579
> Add in missing Skip_Empty_Lines option from issue #579

- administration/scheduling-and-retries.md
Update documentation about retries according with https://github.com/fluent/fluent-bit/pull/3219
> output: update documentation about retries

- pipeline/outputs/elasticsearch.md
> out_es: Amazon is rebranding to Amazon OpenSearch Service

- administration/buffering-and-storage.md
This documentation is related to the storage pause feature implemented in PR fluent/fluent-bit#4077.
> input: describe the file storage pause feature.

- pipeline/outputs/cloudwatch.md
- pipeline/outputs/firehose.md
- pipeline/outputs/kinesis.md
- pipeline/outputs/s3.md
Signed-off-by: Matthew Fala <falamatt@amazon.com>
> output: aws plugins: add auto_retry_requests documentation

- administration/configuring-fluent-bit/configuration-file.md
> Minor grammer improvements

- administration/scheduling-and-retries.md
This is a documentation about https://github.com/fluent/fluent-bit/pull/3219
Note: following https://github.com/fluent/fluent-bit-docs/pull/510#issuecomment-958433808
> administration: scheduler: add 'no_limits' configuration

- pipeline/filters/lua.md
This patch adds "type_array_key" for https://github.com/fluent/fluent-bit/pull/3487
> filter: lua: add description about 'type_array_key'

- pipeline/outputs/influxdb.md
Add documentation for dynamic tags list feature.
Signed-off-by: PetarBersic <petar.bersic@protonmail.com>
> out_influxdb: add dynamic Tags List feature documentation

- pipeline/outputs/websocket.md
update content for websocket output plugin
> [out_websocket] update ws output plugin content

- pipeline/outputs/slack.md
Signed-off-by: Sanya Kochhar <kochhars@microsoft.com>
> outputs: fix slack doc grammar

- pipeline/inputs/syslog.md
> Fix typo in section name

- pipeline/outputs/stackdriver.md
- pipeline/outputs/stackdriver_special_fields.md
> out_stackdriver: add document of special value `trace`

- pipeline/outputs/stackdriver.md
- pipeline/outputs/stackdriver_special_fields.md
… (#629)
Signed-off-by: 0Delta <0deltast@gmail.com>
> pipeline: outputs: stackdriver: add document of special value `trace` (backport #629)

- pipeline/inputs/tail.md
Signed-off-by: Zero King <l2dy@icloud.com>
> input: tail: fix typo (#651)

- SUMMARY.md
> docs: summary: add Configuring Parser

- SUMMARY.md
> docs: summary: add Configuring Parser (#654)

- pipeline/outputs/loki.md
https://github.com/fluent/fluent-bit/pull/2995
https://github.com/fluent/fluent-bit/pull/3069
> pipeline: outputs: loki: document remove_keys and drop_single_key

- pipeline/outputs/loki.md
Signed-off-by: Zero King <l2dy@icloud.com>
> pipeline: outputs: loki: document remove_keys and drop_single_key (#659)

- administration/networking.md
> administration: networking: add docs on connect_timeout_log_error

- administration/networking.md
> administration: networking: add docs on connect_timeout_log_error (#664)

- pipeline/outputs/skywalking.md
This PR relates to https://github.com/fluent/fluent-bit/pull/3592. The docs of Apache SkyWalking output plugin.
> introduce Apache SkyWalking output plugin docs

- pipeline/inputs/tail.md
> in_tail: add inotify_watcher to docs

- pipeline/inputs/tail.md
> in_tail: add inotify_watcher to docs (#667)

- pipeline/outputs/file.md
Signed-off-by: JACQUES Francois <hypnoce@donarproject.org>
> out_file plugin : add option create output directory if does not exist

- pipeline/filters/lua.md
Taken from Slack example by user: https://fluent-all.slack.com/archives/C0CTQGHKJ/p1641927953057600?thread_ts=1641863724.045000&cid=C0CTQGHKJ
> filter_lua: add example of variable processing

- pipeline/filters/grep.md
Taken from Slack: https://fluent-all.slack.com/archives/C0CTQGHKJ/p1641933222072300 
> filter_grep: add example for excluding

- .gitbook.yaml
- SUMMARY.md
- installation/sources/build-and-install.md
> in_fluent_bit_metrics: add links in main pages of docs

- installation/windows.md
> windows: provide sample config (#676)

- pipeline/inputs/forward.md
> in_forward: add doc for new option 'tag_prefix'

- pipeline/inputs/forward.md
> in_forward: add doc for new option 'tag_prefix' (#678)

- pipeline/inputs/tail.md
> in_tail: add docs for Static_Batch_Size

- pipeline/inputs/tail.md
> in_tail: add docs for Static_Batch_Size (#680)

- administration/configuring-fluent-bit/multiline-parsing.md
> multiline_parsing: fix some typos

- installation/linux/debian.md
- installation/linux/raspbian-raspberry-pi.md
- installation/linux/ubuntu.md
> install: linux: add system upgrade recommendation

- SUMMARY.md
> docs: summary: add Fluent Bit Metrics

- pipeline/inputs/exec.md
> exec: container support info (#692)

- installation/docker.md
Master sync of https://github.com/fluent/fluent-bit-docs/pull/693
> docker: update 1.8.12 base image details

- pipeline/filters/multiline-stacktrace.md
> filter_multiline: add docs for new buffered mode

- pipeline/parsers/configuring-parser.md
Signed-off-by: Diogo Recharte <diogorecharte@gmail.com>
> pipeline: parsers: configuring-parser: fix typos

- administration/configuring-fluent-bit/configuration-file.md
Signed-off-by: ethinx <eth2net@gmail.com>
> configuration: change stale link due to CORS (#682)

- SUMMARY.md
- pipeline/inputs/windows-exporter-metrics.md
Signed-off-by: Leonardo Alminana <leonardo@calyptia.com>
> pipeline: inputs: windows_exporter_metrics: initial commit

- installation/sources/download-source-code.md
> source: fix chevron parsing

- .gitbook.yaml
- SUMMARY.md
- installation/sources/build-and-install.md
- pipeline/inputs/windows-event-log-winevtlog.md
Corresponding PR is: https://github.com/fluent/fluent-bit/pull/4179
> winevtlog: Add docs

- pipeline/inputs/forward.md
- pipeline/outputs/forward.md
> forward: fix some typos

- pipeline/parsers/configuring-parser.md
Signed-off-by: Diogo Recharte <diogorecharte@gmail.com>
> pipeline: parsers: configuring-parser: fix typos (#705)

- administration/monitoring.md
clarify health check with more details.
Include tow part:
1. A equation for how to determine health status
2. a example with the equation
3. note that error count and retry count only based on output plugins and worked for all output plugins
> clarify health check with more details

- pipeline/outputs/loki.md
Updates to help prevent misconfiguration like so: https://github.com/fluent/fluent-bit/issues/5016
> loki: clarify URL for GC

- pipeline/inputs/tail.md
> input: tail: remove monitoring section (#735)

- pipeline/parsers/json.md
Signed-off-by: Diogo Recharte <diogorecharte@gmail.com>
> pipeline: parsers: json: fix typos

- pipeline/parsers/json.md
Signed-off-by: Diogo Recharte <diogorecharte@gmail.com>
> pipeline: parsers: json: fix typos (#704)

- pipeline/inputs/systemd.md
Documentation for https://github.com/fluent/fluent-bit/pull/4908
> in_systemd: add lowercase option

- installation/linux/README.md
- installation/linux/amazon-linux.md
- installation/linux/debian.md
- installation/linux/raspbian-raspberry-pi.md
- installation/linux/redhat-centos.md
- installation/linux/ubuntu.md
> linux: reformat key info

- SUMMARY.md
> summary: add nightfall

- administration/configuring-fluent-bit/README.md
> administration: configuration: Document configuration modes

- administration/configuring-fluent-bit/yaml/configuration-file.md
> administration: configuration: change inputs, outputs and filters format

- installation/linux/README.md
- installation/linux/amazon-linux.md
- installation/linux/debian.md
- installation/linux/raspbian-raspberry-pi.md
- installation/linux/redhat-centos.md
- installation/linux/ubuntu.md
> linux: update GPG keys for 1.8.15 refs

- installation/windows.md
> windows: update for 1.9.1 release

- installation/windows.md
> windows: update for 1.8.15 release

- installation/docker.md
> installation: docker: add missing tags to the list

- installation/docker.md
> [backport 1.8] update docker installation page

- installation/macos.md
Corresponds to https://github.com/fluent/fluent-bit/pull/5247.
> Add creating macOS installer instruction

- installation/windows.md
> installation: windows: update installers and checksums for 1.9.2

- installation/getting-started-with-fluent-bit.md
Signed-off-by: Felix Seifert <mail@felix-seifert.com>
> installation: getting-started-with-fluent-bit: Correct spelling of `Sandbox`

- installation/windows.md
> installation: windows: update installers and checksums for 1.9.3

- pipeline/filters/multiline-stacktrace.md
> fitler_multiline: add note that multiline filter must come first

- pipeline/filters/multiline-stacktrace.md
> filter_multiline: add partial_message docs

- administration/buffering-and-storage.md
> Add mem_buf_limit example

- installation/windows.md
> windows: update 1.9.4

- installation/getting-started-with-fluent-bit.md
As indicated by Instruqt support, adding token to embed with token.
> getting-started: ensure we use token for Instruqt

- pipeline/inputs/node-exporter-metrics.md
pipeline: inputs: node-exporter-metric: Fix typo
Signed-off-by: Leo Winter <git@lwinter.de>
> pipeline: inputs: node-exporter-metric: Fix typo

- installation/sources/build-and-install.md
Add info from https://github.com/fluent/fluent-bit/pull/5360
> installation: update for YAML Config var

- installation/windows.md
> windows: update for 1.9.5 checksums

- pipeline/outputs/cloudwatch.md
- pipeline/outputs/firehose.md
- pipeline/outputs/kinesis.md
- pipeline/outputs/s3.md
> aws: add IAM permissions for all plugins

- pipeline/filters/expect.md
This patch is for https://github.com/fluent/fluent-bit/pull/5668
> filters: expect: add 'result_key' property

- installation/docker.md
- installation/windows.md
> docs: update 1.9.6 release info

- installation/docker.md
fix the link text for several release tags
> installation: docker: fix release tag link text

- pipeline/parsers/configuring-parser.md
Closes #847
Signed-off-by: YoussefRizkalla <youssefr@google.com>
> pipeline: parsers: configuring-parser: add docs for skip_empty_values

- pipeline/filters/kubernetes.md
Related to https://github.com/fluent/fluent-bit/pull/5291
Signed-off-by: Thomas Danielsson <thomas.danielsson@sharespine.com>
> pipeline: filters: kubernetes: Add kubelet_host

- administration/configuring-fluent-bit/README.md
Simple update just to capture the flags as they currently are for reference.
Ideally we can further expand on this.
> config: add overview of CLI flags

- installation/docker.md
- installation/windows.md
> installation: updates for 1.9.7 release

- installation/kubernetes.md
This PR fixes a Helm Chart reference.
It is a simple typo.
> Fix Helm Chart reference

- installation/windows.md
Updates for https://github.com/fluent/fluent-bit/issues/5885.
> windows: update checksums for AppVeyor binaries

- pipeline/filters/kubernetes.md
this is for https://github.com/fluent/fluent-bit/pull/4487
Signed-off-by: Michael Voelker <novecento@gmx.de>
> filter_kubernetes: add option kube_token_ttl

- pipeline/outputs/stackdriver.md
Signed-off-by: YoussefRizkalla <youssefr@google.com>
> out_stackdriver: add docs for resource_labels

- pipeline/outputs/azure_kusto.md
Documentation for the new [Kusto output plugin](https://github.com/fluent/fluent-bit/pull/5645)
> Azure Kusto Output Plugin Docs

- administration/configuring-fluent-bit/classic-mode/configuration-file.md
- administration/configuring-fluent-bit/yaml/configuration-file.md
This is a doc PR about https://github.com/fluent/fluent-bit/pull/3401 .
The code was already merged.
> configuration-file: add json.convert_nan_to_null

- pipeline/outputs/observe.md
Signed-off-by: joey-skittlz [joe@observeinc.com](mailto:joe@observeinc.com)
Would kindling like to request to add Observe to Fluent Bit's Pipeline Outputs.
> Add Observe Inc to data outputs page

- pipeline/outputs/observe.md
Signed-off-by: joey-skittlz <joe@observeinc.com>
Signed-off-by: joey-skittlz <joe@observeinc.com>
> Add Observe to pipeline outputs (#858)

- SUMMARY.md
> summary: add observe documentation to summary

- SUMMARY.md
Signed-off-by: David Latorre <david@calyptia.com>
> summary: add observe documentation to summary (#877)

- pipeline/outputs/observe.md
Signed-off-by: joey-skittlz joe@observeinc.com
Neglected to put opening code block around configuration file. 
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1202901766836083
> pipeline: outputs: observe: fix code block surrounding configuration file

- pipeline/inputs/nginx.md
This patch is some fixes for nginx exporter plugin doc.
- Fix title
- Add default values 
- Add `Nginx_Plus` property
- https://github.com/fluent/fluent-bit/pull/4379
> pipeline: inputs: nginx: add default values and nginx_plus

- pipeline/inputs/nginx.md
Signed-off-by: Takahiro Yamashita <nokute78@gmail.com>
Signed-off-by: Takahiro Yamashita <nokute78@gmail.com>
Signed-off-by: David Latorre <david@calyptia.com>
> pipeline: inputs: nginx: add default values and nginx_plus (#865)

- installation/docker.md
- installation/windows.md
Updates to container and Windows checksums.
> release: update for 1.9.8

- administration/networking.md
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1202916352332800
> administration: networking: add missing info

- pipeline/filters/multiline-stacktrace.md
…y support from list
Signed-off-by: RicardoAAD <ricardo@calyptia.com>
> pipeline:filters:multiline-stacktrace removed incorrect entry for ruby support from list

- .gitbook.yaml
- SUMMARY.md
- administration/configuring-fluent-bit/README.md
- installation/sources/build-and-install.md
Following #841 
Signed-off-by: Gershon Papi <papigers93@gmail.com>
> Azure Data Explorer docs leftovers

- concepts/buffering.md
Signed-off-by: elenacbc <elena@calyptia.com>
> concepts: buffering: typo corrected

- concepts/buffering.md
Signed-off-by: elenacbc <elena@calyptia.com>
Signed-off-by: elenacbc <elena@calyptia.com>
> concepts: buffering: typo corrected Backport 908

- pipeline/outputs/syslog.md
This patch is doc PR for https://github.com/fluent/fluent-bit/pull/6067
> out_syslog: add preset configurations

- pipeline/outputs/elasticsearch.md
Related to https://github.com/fluent/fluent-bit/pull/5557
> out_es: Document how to enable payload compress

- pipeline/outputs/stackdriver.md
Signed-off-by: Youssef Rizkalla <youssef.rizkalla1@gmail.com>
> out_stackdriver: fix resource labels validation URL

- SUMMARY.md
- pipeline/filters/wasm.md
- pipeline/inputs/exec_wasi.md
This PR is related to https://github.com/fluent/fluent-bit/pull/5931.
> exec_wasi: wasm: Add documents for Wasm based plugins 

- pipeline/outputs/loki.md
This patch is to add a description about `label_map_path`
https://github.com/fluent/fluent-bit/pull/6040
> out_loki: add label_map_path property

- installation/supported-platforms.md
Signed-off-by: RicardoAAD <ricardo@calyptia.com>
Signed-off-by: RicardoAAD <ricardo@calyptia.com>
> installation:supported-platforms added ubuntu 22.04 to supported platforms list (#907)

- installation/docker.md
- installation/windows.md
> installation: updates for 1.9.9 release

- administration/configuring-fluent-bit/multiline-parsing.md
> administration: configuring: multiline: add limitations

- installation/macos.md
Signed-off-by: elenacbc <elena@calyptia.com>
> installation: macos: added missing step

- installation/upgrade-notes.md
> upgrade: notes on release notes process

- SUMMARY.md
> main: summary: add nginx metrics exporter to menu

- SUMMARY.md
> main: summary: add nginx metrics exporter to menu (#937)

- pipeline/inputs/exec.md
Backport of #943 and resolves https://github.com/fluent/fluent-bit/issues/6236
> exec: update to indicate not supported by containers

- administration/security.md
Signed-off-by: Leonardo Alminana <leonardo@calyptia.com>
> security: added input side TLS information and examples.

- installation/linux/README.md
- installation/linux/amazon-linux.md
- installation/linux/debian.md
- installation/linux/raspbian-raspberry-pi.md
- installation/linux/redhat-centos.md
- installation/linux/ubuntu.md
- installation/upgrade-notes.md
> linux: deprecation of td-agent-bit now removal

- installation/linux/amazon-linux.md
- installation/linux/debian.md
- installation/linux/redhat-centos.md
- installation/linux/ubuntu.md
> linux: update latest versions supported

- development/developer-guide.md
> developer-guide: Add threaded flag description on input plugin

- pipeline/filters/modify.md
These were added in https://github.com/fluent/fluent-bit/pull/6103
Signed-off-by: Dennis Kaarsemaker <dennis@kaarsemaker.net>
> pipeline: filter: modify: document move_to_{start,end}

- .gitbook.yaml
- SUMMARY.md
- installation/sources/build-and-install.md
- pipeline/filters/ecs-metadata.md
> filter_ecs: new filter for AWS ECS Metadata

- pipeline/inputs/opentelemetry.md
Documentation for the OpenTelemetry input plugin
Signed-off-by: Aditya Prajapati <aditya@calyptia.com>
> pipeline: inputs: opentelemetry: add docs

- pipeline/outputs/splunk.md
> pipeline: output: splunk: Add description for sending metrics type of events

- installation/windows.md
- Update the versions and checksums for 2.0 release
Signed-off-by: Jorge Niedbalski <j@calyptia.com>
> docs: update windows docs for 2.0

- installation/docker.md
- installation/windows.md
> installation: update for 2.0 releases

- installation/docker.md
- installation/windows.md
> release: updates for 2.0.4

- installation/linux/amazon-linux.md
- installation/linux/redhat-centos.md
- installation/supported-platforms.md
> linux: add CentOS Stream to supported targets

- pipeline/inputs/syslog.md
https://github.com/fluent/fluent-bit/pull/6348
> pipeline: inputs: syslog: added Receive_Buffer_Size documentation

- installation/linux/ubuntu.md
the order was wrong so it won't start.
> docs: corrects systemd service start command

- installation/docker.md
> docker: add distroless faq

- installation/docker.md
- installation/windows.md
> release: updates for 2.0.5 release

- pipeline/outputs/s3.md
> pipeline: outputs: s3: add warning that prom metrics are meaningless

- pipeline/outputs/firehose.md
Signed-off-by: Clay Cheng <claychen@amazon.com>
> pipeline: outputs: firehose: update doc for time_key_format.

- administration/configuring-fluent-bit/multiline-parsing.md
This is a patch for https://github.com/fluent/fluent-bit/pull/6257
> multiline-parsing: add an example to get structured data from multiline

- pipeline/filters/record-modifier.md
https://github.com/fluent/fluent-bit/pull/6422
This is to add an option `uuid_key`.
> filter_record_modifier: add 'uuid_key' option

- administration/configuring-fluent-bit/classic-mode/configuration-file.md
- administration/configuring-fluent-bit/yaml/configuration-file.md
- administration/scheduling-and-retries.md
Signed-off-by: Drew Zhang <zhayuzhu@amazon.com>
> administration: scheduling-and-retries: add retry waiting time section

- installation/docker.md
- installation/windows.md
> release: update for 2.0.6

- installation/linux/ubuntu.md
Add hint for the following error "Certificate verification failed".
> installation:linux-packages:ubuntu add hint about ca-certificates

- pipeline/outputs/opentelemetry.md
https://github.com/fluent/fluent-bit/pull/6232
> out_opentelemetry: add gzip compression

- administration/configuring-fluent-bit/yaml/configuration-file.md
Resolves https://github.com/fluent/fluent-bit/issues/6408.
> yaml: update for latest syntax

- pipeline/outputs/observe.md
Signed-off-by: Joe Welsh <joe@observeinc.com>
> Update Observe pipeline output

- installation/getting-started-with-fluent-bit.md
- installation/macos.md
> getting-started: add missing targets

- installation/getting-started-with-fluent-bit.md
> getting-started: fix merge typo

- installation/windows.md
> windows: update checksums for 1.9.10

- README.md
Signed-off-by: harytfw <harytfw@outlook.com>
> README: fix wasm filter plugins link

- installation/docker.md
> docker: update for signed verification

- pipeline/inputs/http.md
Similar to the one reported in PR #1000 , update config param for in_http as well
Signed-off-by: Aditya Prajapati <aditya@calyptia.com>
> in_http: change host to listen in config param

- pipeline/outputs/firehose.md
- pipeline/outputs/kinesis.md
> aws: revert time_key docs that I merged before feature release

- administration/security.md
> administration: security: fix broken links to input plugins

- pipeline/inputs/nginx.md
> Backport #1010

- pipeline/outputs/elasticsearch.md
Signed-off-by: Renato Arruda <renato.arruda@schibsted.com>
Signed-off-by: Renato Arruda <renato.arruda@schibsted.com>
> pipeline: outputs: elasticsearch: Document how to enable payload compress… backport #824 to 1.9

- installation/docker.md
- installation/windows.md
> release: update for 2.0.8

- installation/windows.md
> 1.9: windows url tweaks

- pipeline/outputs/kinesis.md
> kinesis_streams: note that partition key is always random

- pipeline/filters/lua.md
Add another use case for lua scripts.
Istio's proxies logs response code filtering use case.
> pipeline: filters: lua: add response code filtering example

- pipeline/outputs/kinesis.md
Signed-off-by: Clay Cheng <claychen@amazon.com>
> pipeline: outputs: kinesis: update doc for time_key_format

- stream-processing/README.md
- stream-processing/getting-started/hands-on.md
- stream-processing/samples/sp-samples-1k.log
- stream-processing/stream-processing.md
Resolves https://github.com/fluent/fluent-bit/discussions/6857 by adding missing samples previously hosted on legacy website.
> stream-processing: add samples from legacy website

- pipeline/outputs/loki.md
Documentation for related PR https://github.com/fluent/fluent-bit/pull/4136
> out_loki: Adding reference to bearer token auth method

- installation/getting-started-with-fluent-bit.md
Fixing the Calyptia Fluent Bit LTS Download link in docs
> installation: getting-started-with-fluent-bit: fix calyptia fluentbit LTS download link

- pipeline/filters/log-to-metrics.md
Documentation for the new https://github.com/fluent/fluent-bit/pull/6674 Log To Metrics Filter Plugin
> Log To Metrics Filter Plugin Documentation

- installation/linux/amazon-linux.md
- installation/linux/redhat-centos.md
- installation/linux/ubuntu.md
- installation/supported-platforms.md
Related to https://github.com/fluent/fluent-bit/pull/7080.
Also resolves https://github.com/fluent/fluent-bit/issues/7015.
> installation: update for AL2023

- administration/buffering-and-storage.md
Documented option storage.delete_irrecoverable_chunks
> Administration: buffering-and-storage: Corrupted chunks deletion

- pipeline/inputs/windows-exporter-metrics.md
This PR is corresponding to https://github.com/fluent/fluent-bit/pull/6766.
> in_windows_exporter_metrics: Add parameters and metrics' descriptions

- pipeline/filters/grep.md
This patch is for https://github.com/fluent/fluent-bit/pull/6721
> pipeline: filters: grep: add logical_op property

- installation/docker.md
- installation/windows.md
Updates for the 2.1.0 release.
> install: updates for 2.1.0 release

- pipeline/filters/aws-metadata.md
https://github.com/fluent/fluent-bit/pull/6065
> filter: aws ec2 tags

- administration/configuring-fluent-bit/yaml/configuration-file.md
The documentation for the incudes option is missing - added  tweaked wording to improve readability
https://github.com/fluent/fluent-bit/issues/7171
Signed-off-by: Phil Wilkins <phil@mp3monster.comorg
> inclusion and readability improvements

- pipeline/inputs/windows-exporter-metrics.md
This PR is corresponding for https://github.com/fluent/fluent-bit/pull/6587.
> in_windows_exporter_metrics: Write down doescriptions for enhancement of Windows Exporter Metrics plugin

- .gitbook.yaml
- SUMMARY.md
- installation/sources/build-and-install.md
- pipeline/inputs/elasticsearch.md
Corresponding PR is: https://github.com/fluent/fluent-bit/pull/6685
> in_elasticsearch: Add a documentation

- pipeline/outputs/kafka.md
Update timestamp format specification.
This change depend on https://github.com/fluent/fluent-bit/pull/6395
Signed-off-by: Lubos Hozzan <hozzan@gmail.com>
> pipeline: outputs: kafka: update spec

- .github/workflows/pr-lint.yaml
- installation/docker.md
- installation/windows.md
- update-release-version-docs.sh
Added automation script as well to use in Fluent Bit automation.
> release: updates for 2.1.2

- pipeline/inputs/kafka.md
- pipeline/outputs/kafka.md
Resolves https://github.com/fluent/fluent-bit/issues/7269
> input: kafka: Add initial documentation

- installation/windows.md
Fixed so that description matches version on files referenced.
> installation: windows: corrected current version

- pipeline/inputs/elasticsearch.md
The corresponding PR is https://github.com/fluent/fluent-bit/pull/7579.
> in_elasticsearch: Add descriptions for elasticsearch server parameter and default values

- .gitbook.yaml
- SUMMARY.md
- pipeline/inputs/splunk.md
Corresponds to https://github.com/fluent/fluent-bit/pull/7349.
> in_splunk: Add documentation for input splunk plugin (Splunk HTTP HEC)

- pipeline/outputs/stackdriver.md
Documentation for https://github.com/fluent/fluent-bit/pull/7101
> Document compression in stackdriver output plugin

- .gitbook.yaml
- SUMMARY.md
- installation/sources/build-and-install.md
- pipeline/inputs/udp.md
Also, added a description for Source_Address_Key parameter.
> in_udp: Add documentation

- pipeline/inputs/http.md
Extend the descriptions and examples in http input
Resolves https://github.com/fluent/fluent-bit/issues/7924
> close #7924 - Update usage and behaviour of tags in http input

- administration/configuring-fluent-bit/README.md
> yaml configuration is production ready

- development/wasm-filter-plugins.md
development: wasm-filter-plugins: add new example using wasm-filter with rust @patrick-stephens
> development: wasm-filter-plugins: add new example using wasm-filter

- SUMMARY.md
cc: @lecaros @patrick-stephens
> add missing link to oracle log analytics plugin

- pipeline/inputs/kubernetes-events.md
Back-port of  PR #1214  to 2.1
> Backport 1214 to 2.1

- administration/configuring-fluent-bit/yaml/configuration-file.md
> administration: update unsupported yaml config features

- pipeline/outputs/prometheus-remote-write.md
Added integration with [Levitate](https://last9.io/levitate-tsdb) for Prometheus Remote Write.
> Add Levitate example for Prometheus Remote Write

- pipeline/inputs/node-exporter-metrics.md
Corresponding PR is: https://github.com/fluent/fluent-bit/pull/8049
> node_exporter_metrics: Add NVMe metrics descriptions

- pipeline/inputs/windows-event-log-winevtlog.md
This PR is corresponding to https://github.com/fluent/fluent-bit/pull/7848.
> in_winevtlog: Add descriptions about xml query for filtering events

- pipeline/outputs/azure_blob.md
out_azure_blob: update Azure Blob output configuration
Update the doc fot the PR: https://github.com/fluent/fluent-bit/pull/8243
Fixes: https://github.com/fluent/fluent-bit/issues/8230
> out_azure_blob: update Azure Blob output configuration

- pipeline/inputs/memory-metrics.md
This patch is to add an example in yaml for in_mem.
> in_mem: add examples for yaml configuration

- pipeline/inputs/disk-io-metrics.md
This patch is to add an example in yaml for in_disk.
> in_disk: add examples for yaml configuration

- pipeline/inputs/mqtt.md
This patch is to add 
| Key | Description |
| :--- | :--- |
| Payload_Key |　Specify the key where the payload key/value will be preserved. |
https://github.com/fluent/fluent-bit/pull/7872
> pipeline: inputs: in_mqtt: add payload_key

- pipeline/inputs/exec.md
This patch is to add an example in yaml for in_exec.
> in_exec: add examples for yaml configuration

- pipeline/inputs/health.md
This patch is to add an example in yaml for in_health.
> in_health: add examples for yaml configuration

- pipeline/inputs/head.md
This patch is to add an example in yaml for in_head.
> in_head: add examples for yaml configuration

- pipeline/inputs/network-io-metrics.md
This patch is to add an example in yaml for in_netif.
> in_netif: add examples for yaml configuration

- pipeline/inputs/random.md
This patch is to add an example in yaml for in_random.
> in_random: add examples for yaml configuration

- pipeline/inputs/systemd.md
This patch is to add an example in yaml for in_systemd.
> in_systemd: add examples for yaml configuration

- pipeline/inputs/thermal.md
This patch is to add an example in yaml for in_thermal.
> in_thermal: add examples for yaml configuration

- pipeline/inputs/statsd.md
This patch is to add an example in yaml for in_statsd.
> in_statsd: add examples for yaml configuration

- pipeline/outputs/websocket.md
See https://github.com/fluent/fluent-bit/pull/8536.
> out_websocket: Document ability to provide additional headers

- CODEOWNERS
- CONTRIBUTING.md
- MAINTAINERS.md
this PR updates the Fluent Bit contributor guide.
> contributing: add sections and update phrasing

- concepts/data-pipeline/buffer.md
- concepts/data-pipeline/filter.md
- concepts/data-pipeline/input.md
- concepts/data-pipeline/output.md
- concepts/data-pipeline/parser.md
- concepts/data-pipeline/router.md
Signed-off-by: Alexa Kreizinger <alexakreizinger@gmail.com>
> Replace "Concepts" images with Mermaid charts

- README.md
this PR adds a note about Chronosphere's sponsorship of Fluent Bit, and also cleans up a handful of words in the intro sentence that were capitalized but don't need to be.
> Update top-level page with note about Chronosphere sponsorship

- .gitignore
- pipeline/inputs/dummy.md
Also added `.DS_Store` in gitignore for Mac OS
> pipeline: inputs: dummy: Add column for default values

- pipeline/inputs/mqtt.md
- Add column for default value
- Format table
> pipeline: inputs: mqtt: Format configuration parameter table

- pipeline/inputs/kubernetes-events.md
> pipeline: inputs: kubernetes-events: Fix typo

- pipeline/outputs/prometheus-remote-write.md
Pointed out at https://github.com/fluent/fluent-bit/issues/9259#issuecomment-2307014864.
> out_prometheus_remote_write: Add an example for Prometheus like labels

- pipeline/outputs/s3.md
> Style cleanup for S3

- README.md
- SUMMARY.md
bump master to 3.2.
All new required commits must be backported to branch 3.1
> main: bump to 3.2

- about/license.md
Provides an extremely minor grammar/style update.
> fluent: docs: minor style fix

- about/what-is-fluent-bit.md
This PR does some basic style updates. 
There are still some vale and markdownlint suggestions, but a couple of them are spurious and are left due to the nature of this particular page. In particular, 3 of them are due to the embedded video, and I don't want to change anything about that.
> fluent: docs: style updates for what is page

- administration/configuring-fluent-bit/classic-mode/configuration-file.md
- vale-styles/FluentBit/Spelling-exceptions.txt
This includes the work from @tomy8s in #604, along with other general style updates.
> config: file: Updating configuraton file for style

- installation/sources/build-and-install.md
- vale-styles/FluentBit/Spelling-exceptions.txt
Brings the page up to general style guidelines, but I didn't add most of the things to the spelling dictionary.
> Install: bring build doc up to date for style

- SUMMARY.md
- pipeline/inputs/ebpf.md
Reference https://github.com/fluent/fluent-bit/pull/9576
> in_ebpf: add documentation for experimental plugin

- pipeline/inputs/forward.md
Corresponding to https://github.com/fluent/fluent-bit/pull/9681
> in_forward: Add a description for empty_shared_key

- pipeline/outputs/stackdriver.md
See https://github.com/fluent/fluent-bit/pull/9779 for details.
> stackdriver: add cloud_logging_base_url docs

- SUMMARY.md
Just missed this with the original PR, so adding traces to get proper document indexing on the site.
> Added traces entry to the docs index.

- administration/configuring-fluent-bit/yaml/parsers-section.md
Updates the selected page to meet style guidelines.
> Admin:config:yaml:parsers Style updates

- administration/configuring-fluent-bit/yaml/configuration-file.md
Mostly brings the selected file into baseline style standards.
> yaml config style updates

- development/wasm-input-plugins.md
> development: wasm-input: general cleanup

- pipeline/pipeline-monitoring.md
> Pipeline: monitoring: style cleanup

- pipeline/filters/multiline-stacktrace.md
Updating the page for consistent style.
> Pipeline: filters: multiline: Style

- vale-styles/FluentBit/WordList.yml
Add test for blacklist/whitelist per Google style.
> Adding allow/blocklist substitution to vale

- pipeline/outputs/loki.md
- vale-styles/FluentBit/Spelling-exceptions.txt
Updating for style and also to try to address question in #1583
> Pipeline: output: loki: style

- .gitignore
- pipeline/outputs/loki.md
Added YAML examples to output plugin loki docs. Also added my ide to the gitignore file in this update. Updates #1723.
> Added YAML examples to output plugin loki docs. Updates #1723.

- administration/configuring-fluent-bit/multiline-parsing.md
Added YAML examples for admin configuring Fluent Bit multiline parsing docs. Fixes #1757.
> Added YAML examples for admin configuring Fluent Bit multiline parsing docs. Fixes #1757.

- pipeline/inputs/process-exporter-metrics.md
> Pipeline: input: process exporter: style

- pipeline/parsers/configuring-parser.md
> pipeline: parsers: configuring-parser: general cleanup

- pipeline/outputs/azure_blob.md
> Pipeline: output: azure blob: style

- pipeline/outputs/bigquery.md
- vale-styles/FluentBit/Headings.yml
- vale-styles/FluentBit/Spelling-exceptions.txt
> pipeline: output: bigquery: style

- pipeline/outputs/firehose.md
- vale-styles/FluentBit/Headings.yml
> Pipeline: output: firehose: style

- pipeline/outputs/gelf.md
- vale-styles/FluentBit/Headings.yml
- vale-styles/FluentBit/Spelling-exceptions.txt
> Pipeline: output: gelf: style

- pipeline/outputs/http.md
- vale-styles/FluentBit/Headings.yml
> Pipeline: output: http: style

- pipeline/processors/sampling.md
> pipeline: processors: sampling: general cleanup

- pipeline/outputs/opentelemetry.md
> Pipeline: output: opentelemetry: style

- SUMMARY.md
- development/developer-guide.md
- local-testing/validating-your-data-and-structure.md
> Local testing, Stream processing, FB for devs: update titles to sentence case

- administration/configuring-fluent-bit/README.md
Updated classic mode deprecation date to end 2026. Fixes #2001.
> Updated classic mode deprecation date to end 2026. Fixes #2001.
